Fix/parallel eth_getlogs
NethermindEth/nethermind pull request #2334
Opened 2020-09-24 22:33 UTC by LukaszRozmej

2020-09-24 22:56 UTC, tkstanczak commented on src/Nethermind/Nethermind.JsonRpc/IJsonRpcConfig.cs
> +        bool BufferResponses { get; set; }
why removed public?

2020-09-24 23:15 UTC, LukaszRozmej commented on src/Nethermind/Nethermind.JsonRpc/IJsonRpcConfig.cs
> +        bool BufferResponses { get; set; }
its default implementation then, its interface. Will get confusing

2020-09-25 22:25 UTC, tkstanczak requested changes
needs tests for the timeout

2020-09-26 00:53 UTC, tkstanczak approved these changes

2020-09-26 01:36 UTC, merged