Fix parity_netPeers and add more tests
NethermindEth/nethermind pull request #2749
Opened 2021-02-03 18:21 UTC by marcindsobczak

I needed to add IP2PProtocolHandler to be able to substitute Caps in ParityModuleTests. We recognized, that it's a good moment to clean up a little and move whole capability-connected content from IProtocolHandler to this new IP2PProtocolHandler and clean up in classes, which were unnecessarily implementing it.

Added:
* test for empty ActivePeers
* test for null ActivePeers
* test for empty Caps

2021-02-03 19:50 UTC, LukaszRozmej approved these changes
minor changes, but otherwise good.

2021-02-03 19:50 UTC, LukaszRozmej commented on src/Nethermind/Nethermind.JsonRpc.Test/Modules/ParityModuleTests.cs
> +        private IParityModule _parityModuleC;
parity module B & C are used only in 1 test, they can be constructed there as variables

2021-02-03 19:50 UTC, LukaszRozmej commented on src/Nethermind/Nethermind.Network/P2P/P2PProtocolHandler.cs
> +        private List<Capability> AgreedCapabilitiesList { get; }
wrong naming scheme _agreedCapabilitiesList

2021-02-03 20:53 UTC, tkstanczak requested changes
NDM solution got broken, open NDM.sln and fix the build then commit

2021-02-04 10:36 UTC, tkstanczak approved these changes

2021-02-04 10:36 UTC, merged