Uses the first segment of the path instead of the last for web socket module name.
NethermindEth/nethermind pull request #2779
Opened 2021-02-11 12:33 UTC by MicahZoltu

This allows modules to utilize the rest of the path for module-specific things like `ws://nethermind:8545/my_module/watch/contract_address/`.

2021-02-11 12:34 UTC, MicahZoltu commented
Note: I *think* this will do what I want, but I don't know how to test it and I don't see any existing tests that cover WS plugin pathing, so I strongly recommend someone review this carefully.

2021-02-12 13:58 UTC, LukaszRozmej approved these changes

2021-02-12 14:14 UTC, LukaszRozmej requested changes
Generally fine, but we need to use RemoveEmptyEntries in split https://docs.microsoft.com/en-us/dotnet/api/system.stringsplitoptions?view=net-5.0 or we will always get an empty string in first

2021-02-12 14:48 UTC, LukaszRozmej approved these changes

2021-02-12 18:32 UTC, merged