Mitigate long branches issues on application restarts
NethermindEth/nethermind pull request #2918
Opened 2021-03-24 16:04 UTC by MarekM25

2021-03-24 16:08 UTC, tkstanczak commented on src/Nethermind/Nethermind.Blockchain/Visitors/StartupBlockTreeFixer.cs
> +                Block parentBlock = _blockTree.FindBlock(block.ParentHash,
parentBlock.FindParent blockw ould be much more efficient here?

2021-03-24 16:08 UTC, tkstanczak commented on src/Nethermind/Nethermind.Blockchain/Visitors/StartupBlockTreeFixer.cs
> +                Block parentBlock = _blockTree.FindBlock(block.ParentHash,
public static BlockHeader? FindParentHeader(this IBlockFinder finder, BlockHeader header, BlockTreeLookupOptions options)

2021-03-24 16:08 UTC, tkstanczak requested changes
this would be better, I think: public static BlockHeader? FindParentHeader(this IBlockFinder finder, BlockHeader header, BlockTreeLookupOptions options)

2021-03-26 13:45 UTC, LukaszRozmej approved these changes

2021-03-26 13:45 UTC, LukaszRozmej commented on src/Nethermind/Nethermind.Blockchain/Visitors/StartupBlockTreeFixer.cs
> +        public StartupBlockTreeFixer(
couldn't we reuse DbBlocksLoader in some way?

2021-03-27 10:37 UTC, merged