1559
NethermindEth/nethermind pull request #3023
Opened 2021-04-28 07:48 UTC by MarekM25

@tkstanczak if you want to review only the last changes you can check https://github.com/NethermindEth/nethermind/compare/xdai1559_tests...1559?expand=1

@LukaszRozmej I would like to see your review and after that, I will run some nodes with those changes schedule smoke tests, and run goerli validator

2021-05-04 10:03 UTC, LukaszRozmej requested changes

2021-05-04 10:03 UTC, LukaszRozmej commented on src/Nethermind/Nethermind.Runner/Ethereum/Steps/StartBlockProducerAuRa.cs
> +                _api.SpecProvider);;
double ;

2021-05-04 13:39 UTC, MarekM25 commented on src/Nethermind/Nethermind.Blockchain/Comparers/GasPriceTxComparerHelper.cs
> +    public static class GasPriceTxComparerHelper
Let's discuss

2021-05-04 13:40 UTC, MarekM25 commented on src/Nethermind/Nethermind.Blockchain/Producers/TxPoolTxSource.cs
> +                if (!HasEnoughFounds(remainingBalance, tx, isEip1559Enabled, _blockPreparationContextService.BaseFee))
Let's discuss

2021-05-04 13:41 UTC, MarekM25 commented on src/Nethermind/Nethermind.Consensus.AuRa/Transactions/TxGasPrice1559Sender.cs
> +    public class TxGasPrice1559Sender : ITxSender
Yes. Please check TxGasPrice1559Sender references

2021-05-04 13:47 UTC, MarekM25 commented on src/Nethermind/Nethermind.Consensus.Ethash/NethDevPlugin.cs
> +                new TransactionComparerProvider(getFromApi.SpecProvider, getFromApi.BlockTree);
We always pass blockTree when we're expecting IBlockFinder. Changed to readonlyBlockTree. Let's discuss

2021-05-04 13:51 UTC, MarekM25 commented on src/Nethermind/Nethermind.Consensus/Transactions/BaseFeeTxFilter.cs
> +            }
Let's discuss

2021-05-05 11:31 UTC, LukaszRozmej approved these changes

2021-05-06 07:38 UTC, merged