Added DslRpcModule tests for now, full tests coming after approval
NethermindEth/nethermind pull request #3116
Opened 2021-06-11 23:29 UTC by gheise

2021-06-13 07:50 UTC, tkstanczak reviewed
Great stub, are they to test if no exception is thrown?
How is the plugin connected with RPC in the setup?

@SebastianDremo would you have a look?

2021-06-13 14:56 UTC, SebastianDremo requested changes
Overall good start but changes need to be done before merging - when writing test names try naming like this  -> when_something_does_not_throws or when_something_returns_correctly
or even more complex [naming standards](https://osherove.com/blog/2005/4/3/naming-standards-for-unit-tests.html)

2021-06-13 14:56 UTC, SebastianDremo commented on src/Nethermind/Nethermind.Dsl.Test/DslRpcModuleTests.cs
> +            _dslRpcModule = new DslRpcModule();
this is not up to date with current DSL branch, right now DslRpcModule takes api, logger and collection of interpreters from plugin (all of them will need to be mocked here)

2021-06-13 14:56 UTC, SebastianDremo commented on src/Nethermind/Nethermind.Dsl.Test/DslRpcModuleTests.cs
> +           _dslRpcModule.dsl_addScript("WATCH House WHERE Author IS 0x22eA9f6b28DB76A7162054c05ed812dEb2f519Cd PUBLISH WebSockets ytext");
the test name does not tell me what we want to check here, do we want to test whether there will be any errors or if an interpreter will be added to the pool with unsupported WATCH value?

2021-06-13 14:56 UTC, SebastianDremo commented on src/Nethermind/Nethermind.Dsl.Test/DslRpcModuleTests.cs
> +        public async Task undefined_condition_test(String script)
same

2021-06-13 14:56 UTC, SebastianDremo commented on src/Nethermind/Nethermind.Dsl.Test/DslRpcModuleTests.cs
> +        public async Task undefined_operation_test(String script)
same

2021-06-13 14:56 UTC, SebastianDremo commented on src/Nethermind/Nethermind.Dsl.Test/DslRpcModuleTests.cs
> +        public async Task undefined_syntax_test(String script)
same

2021-06-13 14:56 UTC, SebastianDremo commented on src/Nethermind/Nethermind.Dsl.Test/DslRpcModuleTests.cs
> +        public async Task undefined_condition_test(String script)
same, and also it is not undefined condition, rather undefined WATCH value

2021-06-13 14:56 UTC, SebastianDremo commented on src/Nethermind/Nethermind.Dsl.Test/DslRpcModuleTests.cs
> +           await _dslPlugin.Init(_api);
there is no need for DslPlugin.Init() here since rpc module is kinda standalone, check what Init() does and then see what rpc module does

2021-06-16 08:03 UTC, SebastianDremo commented on src/Nethermind/Nethermind.Dsl.Test/DslRpcModuleTests.cs
> +            _dslRpcModule.AddInterpreter(_interpreters)
how do we know whether it was added correctly? 
there is no assert

2021-06-16 08:05 UTC, SebastianDremo commented on src/Nethermind/Nethermind.Dsl.Test/DslRpcModuleTests.cs
> +            _dslRpcModule.dsl_addScript("WATCH WHERE 23 IS NOT 23 PUBLISH WebSockets ytext");
no assertion

2021-06-16 08:06 UTC, SebastianDremo commented on src/Nethermind/Nethermind.Dsl.Test/DslRpcModuleTests.cs
> +            _dslRpcModule.dsl_addScript("WHERE Author IS 0x22eA9f6b28DB76A7162054c05ed812dEb2f519Cd WATCH Blocks PUBLISH WebSockets ytext");
no assertion, test means nothing

2021-06-16 08:06 UTC, SebastianDremo commented on src/Nethermind/Nethermind.Dsl.Test/DslRpcModuleTests.cs
> +            _dslRpcModule.dsl_addScript("WATCH Blocks WHERE AUTHOR IS 0x22eA9f6b28DB76A7162054c05ed812dEb2f519Cd STOP PUBLISH WebSockets ytext");
same

2021-06-16 08:07 UTC, SebastianDremo commented on src/Nethermind/Nethermind.Dsl.Test/DslRpcModuleTests.cs
> +        private Dictionary<int, Interpreter> _interpreter;
hmmm, here is _interpreter and later you use _interpreters,
will those tests even compile?

2021-07-08 14:08 UTC, closed without merging