Rpc example
NethermindEth/nethermind pull request #3225
Opened 2021-07-13 12:28 UTC by kjazgar

Fixes | Closes | Resolves #

> Anything marked as optional that you didn't need to fill in, please remove it from the PR description. Choose one of the keywords above to refer to the issue this PR solves, followed by the issue number (e.g Fixes # 666). If there is no issue, remove the line. Remove this note after reading.

## Changes:
-

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ x] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Other (please describe): 

## Testing
**Requires testing**

- [ ] Yes
- [x ] No

**In case you checked yes, did you write tests??**

- [ ] Yes
- [x ] No

**Comments about testing , should you have some** (optional)

## Further comments (optional)

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

2021-07-13 14:12 UTC, LukaszRozmej approved these changes

2021-07-13 14:38 UTC, MarekM25 requested changes
Thank you for this PR.
Please, ask @marcindsobczak how to generate docs from it. 
Please, add more sophisticated examples than just zeroes :)

2021-07-13 14:38 UTC, MarekM25 commented on src/Nethermind/Nethermind.JsonRpc/Modules/Eth/IEthRpcModule.cs
> +            ExampleResponse = "0x0")]
Could you return different examples than 0x0? :)

2021-07-13 14:38 UTC, MarekM25 commented on src/Nethermind/Nethermind.JsonRpc/Modules/Eth/IEthRpcModule.cs
> +            ExampleResponse = "0x0")]
And here?

2021-07-13 14:38 UTC, MarekM25 commented on src/Nethermind/Nethermind.JsonRpc/Modules/Eth/IEthRpcModule.cs
> +            ExampleResponse = "0x0")]
And in more places :)

2021-07-16 10:09 UTC, marcindsobczak approved these changes

2021-07-16 10:12 UTC, MarekM25 approved these changes

2021-07-21 12:17 UTC, merged