changed healthchecks notifications
NethermindEth/nethermind pull request #3246
Opened 2021-07-26 08:21 UTC by aajj999

## Changes:
Modified health checks notifications, so that they give more information (description if node is unhealthy, node name, hostname, ip).

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Other (please describe): 

## Testing
**Requires testing**

- [ x] Yes
- [ ] No

**In case you checked yes, did you write tests??**

- [x ] Yes
- [ ] No

2021-07-26 08:27 UTC, matilote approved these changes

2021-07-26 08:32 UTC, MarekM25 requested changes

2021-07-26 08:32 UTC, MarekM25 commented on src/Nethermind/Nethermind.HealthChecks/HealthChecksWebhookInfo.cs
> +        public HealthChecksWebhookInfo(string description, IPAddress externalIp, string nodeName)
I suggest using _api.IpResolver and IMetricsConfig in constructor instead of IPAddress and nodeName

2021-07-26 08:32 UTC, MarekM25 commented on src/Nethermind/Nethermind.HealthChecks/HealthChecksWebhookInfo.cs
> +
Cosmetic formatting: please, remove extra empty lines

2021-07-26 08:32 UTC, MarekM25 commented on src/Nethermind/Nethermind.HealthChecks.Test/HealthChecksWebhookInfoTests.cs
> +            expected = "`" + description + "`" + Environment.NewLine
Instead of concatenate strings for expected value I recommend write the full string that you're expecting and mock Ip Resolver

2021-07-27 07:31 UTC, MarekM25 approved these changes

2021-07-27 11:38 UTC, merged