Fix BlockParameter parsing for filters
NethermindEth/nethermind pull request #3267
Opened 2021-07-30 10:14 UTC by LukaszRozmej

Closes #3265 PR

## Changes:
Remove obsolete (and buggy) deserialization.

## Types of changes

What types of changes does your code introduce?

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Other (please describe): 

## Testing
**Requires testing**

- [ ] Yes
- [x] No

**In case you checked yes, did you write tests??**

- [ ] Yes
- [x] No

2021-07-30 10:41 UTC, MicahZoltu approved these changes
Thanks!

2021-08-02 13:07 UTC, MarekM25 requested changes
Could you add any test or explain why we don't need it?

2021-08-02 13:07 UTC, MarekM25 commented on src/Nethermind/Nethermind.JsonRpc/Data/BlockParameterConverter.cs
>                  case { } latest when latest.Equals("earliest", StringComparison.InvariantCultureIgnoreCase):
[you_can_ignore_it] latest and renaming?

2021-08-02 13:11 UTC, LukaszRozmej commented
We removed unused code, moved to better, actually tested one.

2021-08-02 13:23 UTC, MarekM25 approved these changes

2021-08-02 22:04 UTC, merged