Bundle included metrics
NethermindEth/nethermind pull request #3331
Opened 2021-08-24 15:09 UTC by LukaszRozmej

Closes #3328

## Changes:
Add bundle included metrics

## Types of changes

What types of changes does your code introduce?

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Other (please describe): 

## Testing
**Requires testing**

- [x] Yes
- [ ] No

**In case you checked yes, did you write tests??**

- [x] Yes
- [ ] No

2021-08-24 15:21 UTC, marcindsobczak approved these changes

2021-08-24 15:26 UTC, tkstanczak requested changes
do not analyze this way, just add++ when included

2021-08-30 11:36 UTC, tkstanczak commented on src/Nethermind/Nethermind.Mev.Test/MevRpcModuleTests.TestMevRpcBlockchain.cs
> +                MevBlockProducerTransactionsExecutorFactory mevExecutorFactory = new(SpecProvider, LogManager);
this looks already too complicated...

2021-08-30 11:38 UTC, tkstanczak requested changes
too complex for the task

2021-08-30 11:39 UTC, tkstanczak commented on src/Nethermind/Nethermind.Mev/MevBlockProducer.cs
> +                        UInt256 balance = mevBlockProducerInfo.BeneficiaryTracer.BeneficiaryBalance;
law of demeter broken

2021-08-30 11:40 UTC, tkstanczak commented on src/Nethermind/Nethermind.Mev/MevBlockProducer.cs
> +                            bundlesAdded = mevBlockProducerInfo.BundlesIncludedTracer.BundlesIncluded;
law of demeter broken

2021-08-30 11:40 UTC, tkstanczak commented on src/Nethermind/Nethermind.Mev/MevBlockProducerTransactionsExecutorFactory.cs
> +            LastExecutor = new MevBlockProductionTransactionsExecutor(readOnlyTxProcessingEnv, _specProvider, _logManager);
factory should be stateless if possible, looks like much complexity added

2021-08-31 12:20 UTC, closed without merging