Renamed consensus to engine.
NethermindEth/nethermind pull request #3357
Opened 2021-08-30 14:55 UTC by kjazgar

Fixes | Closes | Resolves #

## Changes:
Renamed consensus to engine in Nethermind.Merge.Plugin and Nethermind.Merge.Plugin.Test.

## Types of changes

What types of changes does your code introduce?

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Other (please describe): 

## Testing
**Requires testing**

- [ ] Yes
- [x] No

2021-08-31 14:56 UTC, MarekM25 approved these changes

2021-09-01 14:03 UTC, LukaszRozmej commented on src/Nethermind/Nethermind.Merge.Plugin.Test/ConsensusModuleTests.Setup.cs
> +        private IEngineRpcModule CreateConsensusModule(MergeTestBlockchain chain)
Rename file too

2021-09-01 14:04 UTC, LukaszRozmej commented on src/Nethermind/Nethermind.Merge.Plugin.Test/ConsensusModuleTests.cs
> +            IEngineRpcModule rpc = CreateConsensusModule(chain);
Rename file too

2021-09-01 14:04 UTC, LukaszRozmej requested changes
Please rename test files to match the tested classes

2021-09-02 14:29 UTC, LukaszRozmej approved these changes

2021-09-02 14:29 UTC, merged