change ITxFilter to be like IIncomingTxFilter
NethermindEth/nethermind pull request #3626
Opened 2021-11-19 19:23 UTC by marcindsobczak

Fixes | Closes | Resolves #

> Anything marked as optional that you didn't need to fill in, please remove it from the PR description. Choose one of the keywords above to refer to the issue this PR solves, followed by the issue number (e.g Fixes # 666). If there is no issue, remove the line. Remove this note after reading.

## Changes:
-

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Other (please describe): 

## Testing
**Requires testing**

- [ ] Yes
- [ ] No

**In case you checked yes, did you write tests??**

- [ ] Yes
- [ ] No

**Comments about testing , should you have some** (optional)

## Further comments (optional)

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

2021-11-22 20:58 UTC, kjazgar approved these changes

2021-11-22 23:16 UTC, LukaszRozmej requested changes
We still have both ITxFilter and IIncomingTxFilter, we should unify and simplify. Then delete the obsolete one.

This is good first step but not enough for proper refactor.

2021-11-22 23:16 UTC, LukaszRozmej commented on src/Nethermind/Nethermind.Consensus/Transactions/NullTxFilter.cs
> +        public (bool Allowed, AddTxResult? Reason) IsAllowed(Transaction tx, BlockHeader parentHeader) => (true, null);
As we have AddTxResult.Added, we don't need the tuple now, we can simplify this a lot.

2021-11-22 23:16 UTC, LukaszRozmej commented on src/Nethermind/Nethermind.TxPool/AddTxResult.cs
> +        PermissionDeniedForThisTxType,
just PermissionDenied

2021-11-22 23:16 UTC, LukaszRozmej commented on src/Nethermind/Nethermind.TxPool/AddTxResult.cs
> +        PermissionDeniedForThisTxType,
Also I don't love the fact that POSDAO based specific result now got into here. Maybe we could make AddTxResult a struct tha would have:
1) Number
2) Code
3) Optional custom message?

Then other modules when extending TxPool could return their won results.

2021-12-05 21:11 UTC, LukaszRozmej commented on src/Nethermind/Nethermind.Blockchain/TxFilterAdapter.cs
> +                if (!acceptTxResult.Equals(AcceptTxResult.Accepted))
implicit bool cast

2021-12-05 21:11 UTC, LukaszRozmej commented on src/Nethermind/Nethermind.Baseline.Test/BaselineTreeTracker_ReorganizationTests.cs
> +                if (!result.Equals(AcceptTxResult.Accepted))
implicit bool cast

2021-12-06 14:22 UTC, LukaszRozmej approved these changes
We could rename "result" to "accepted" or "allowed" in many places now so it would be more readable with those if's.

2021-12-06 14:22 UTC, LukaszRozmej commented on src/Nethermind/Nethermind.TxPool/AcceptTxResult.cs
> +        public bool Equals(AcceptTxResult result) => Id == result.Id;
add implementation IEquatable<AcceptTxResult>

2021-12-06 14:22 UTC, LukaszRozmej commented on src/Nethermind/Nethermind.TxPool/AcceptTxResult.cs
> +        public static implicit operator bool(AcceptTxResult result) => result.Id == 0;
can we go with result.Id == Accepted.Id ?

2021-12-06 14:39 UTC, LukaszRozmej commented on src/Nethermind/Nethermind.TxPool/AcceptTxResult.cs
> +        public static implicit operator bool(AcceptTxResult result) => result.Id == 0;
Or maybe make it a const here and there

2021-12-06 15:08 UTC, merged

2022-11-24 01:10 UTC, prashantkumar1982 commented
This PR broke Chainlink integration.
The refactoring of error message broke our regular expression matching logic, which tells us why a Tx failed, and makes our StateMachine work.

A partial fix that Chainlink needed on our side is here: https://github.com/smartcontractkit/chainlink/pull/7989

@marcindsobczak in future, please keep this in mind, and possibly, could you notify Chainlink before changing error response strings?

2022-11-24 09:20 UTC, marcindsobczak commented
Thank you @prashantkumar1982 for a message. We highly appreciate such a feedback, although we don't have a knowledge how your setup works, so it would be hard to catch which changes can possibly affect it. Possible solution could be to add integration tests which we can run on our CI. Could you please provide us such a tests? We would love to add it to our codebase and then it will be easy to remember to ping you every time when we change something and tests start failing

2022-11-24 11:38 UTC, dimriou commented
Hey @marcindsobczak , thanks for the suggestions. We'll discuss this internally and let you know. 

For reference, here (https://github.com/smartcontractkit/chainlink/blob/develop/core/chains/evm/client/errors.go#L170) you can find the regexes we use to match Nethermind's RPC responses. Depending on each response, we make a different decision on how to handle our pending transactions. As @prashantkumar1982 mentioned, if the regexes change this means that our Nodes will not be able to handle some of the responses, thus affecting our pending transactions.