[AA] Only allow max 10 User Operation per sender, Implement op fee replacement
NethermindEth/nethermind pull request #3799
Opened 2022-02-08 18:28 UTC by kristofgazso

Fixes | Closes | Resolves #3790  #3798

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Other (please describe): 

## Testing
**Requires testing**

- [x] Yes
- [ ] No

**In case you checked yes, did you write tests??**

- [x] Yes
- [ ] No

2022-02-08 20:00 UTC, LukaszRozmej commented on src/Nethermind/Nethermind.AccountAbstraction/Source/UserOperationSortedPool.cs
> +            if (GetBucketSnapshot().TryGetValue(op.Sender, out UserOperation[]? opsForSender))
Doing a Snapshot is costly - its a copy of the whole thing, is it needed here?

2022-02-08 21:49 UTC, LukaszRozmej requested changes
small issues to fix

2022-02-08 22:41 UTC, LukaszRozmej approved these changes

2022-02-09 10:04 UTC, marcindsobczak approved these changes

2022-02-09 10:34 UTC, merged