[AA] Only increment paymaster counter when ops become includable, only allow acceptance of ops above minimum threshold compared to baseFee
NethermindEth/nethermind pull request #3967
Opened 2022-04-20 08:06 UTC by kristofgazso

## Changes:
-

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Other (please describe): 

## Testing
**Requires testing**

- [x] Yes
- [ ] No

**In case you checked yes, did you write tests??**

- [x] Yes
- [ ] No

2022-04-20 12:00 UTC, LukaszRozmej requested changes

2022-04-20 12:00 UTC, LukaszRozmej commented on src/Nethermind/Nethermind.AccountAbstraction/Source/UserOperationPool.cs
> +                    UInt256 baseFee = CalculateCurrentBaseFee();
Calculating twice - here and in Validate, calculate once before validate, and pass it to validate.

2022-04-20 12:00 UTC, LukaszRozmej commented on src/Nethermind/Nethermind.AccountAbstraction/Source/UserOperationPool.cs
> +            UInt256 baseFee = CalculateCurrentBaseFee();
avoid double calculation

2022-05-13 12:16 UTC, kristofgazso commented on src/Nethermind/Nethermind.AccountAbstraction/Source/UserOperationPool.cs
> +                userOperation.PassedBaseFee = true;
nope, because that could open a potential dos possibility by allowing the sender to keep filling up the mempool more easily

2022-05-13 13:12 UTC, kristofgazso commented on src/Nethermind/Nethermind.AccountAbstraction/Source/UserOperationPool.cs
> +                .GetSnapshot()
moved it to sortedpool, lmk if it looks good

2022-05-30 09:43 UTC, LukaszRozmej commented on src/Nethermind/Nethermind.AccountAbstraction/Source/PaymasterThrottler.cs
> +            if (GetOpsIncluded(paymaster) <= minExpectedIncluded + BanSlack) return PaymasterStatus.Throttled;
Than EIP pseudocode sucks too, not a great explanation :P

2022-05-30 09:46 UTC, LukaszRozmej approved these changes

2022-05-31 06:32 UTC, merged