Fix/syncmode
NethermindEth/nethermind pull request #4273
Opened 2022-07-12 16:24 UTC by JKSenthil

Fixes | Closes | Resolves #

> Anything marked as optional that you didn't need to fill in, please remove it from the PR description. Choose one of the keywords above to refer to the issue this PR solves, followed by the issue number (e.g Fixes # 666). If there is no issue, remove the line. Remove this note after reading.

## Changes:
-

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x ] Documentation Update
- [ x] Code style update (formatting, renaming)
- [ ]x Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Other (please describe): 

## Testing
**Requires testing**

- [ ] Yes
- [ x] No

**In case you checked yes, did you write tests??**

- [ ] Yes
- [ ] No

**Comments about testing , should you have some** (optional)

## Further comments (optional)

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

2022-07-13 00:15 UTC, LukaszRozmej requested changes
1. So now setting the Mode changes the Obsolete, so now when we want to remove Obsolete stuff we need to rewrite code. It should be the other way around, Obsolete stuff should only set the new Mode.

2. Clash with Parallel.SyncMode is a bit unfortunate, maybe we should revert changes and rename it to StateSyncMode?

2022-07-13 00:15 UTC, LukaszRozmej commented on src/Nethermind/Nethermind.Blockchain/Synchronization/ISyncConfig.cs
> +        ConfigSyncMode Mode { get; set; }
Add ConfigItem attribute

2022-07-13 00:15 UTC, LukaszRozmej commented on src/Nethermind/Nethermind.Blockchain/Synchronization/SyncConfig.cs
> +            set => _fastSync = value;
shouldn't set change the Mode?

2022-07-13 00:15 UTC, LukaszRozmej commented on src/Nethermind/Nethermind.Blockchain/Synchronization/SyncConfig.cs
> +            get => (Mode == ConfigSyncMode.SnapSync) || (Mode == ConfigSyncMode.NotConfigured && _snapSync);
shouldn't set change the Mode?

2022-07-13 00:15 UTC, LukaszRozmej commented on src/Nethermind/Nethermind.Config/ConfigProvider.cs
> +                                            _logger.Warn("Attribute " + name + " is going to be deprecated. Please use SyncMode=" + name + " in your config instead.");
Use interpolated string

2022-07-14 09:25 UTC, LukaszRozmej commented
> > 
> 
> should I change Parallel.SyncMode to Parallel.StateSyncMode?

No the other way around, change this SyncMode enum to StateSyncMode enum

2022-08-22 02:25 UTC, smartprogrammer93 approved these changes

2023-01-23 14:56 UTC, tkstanczak commented
@LukaszRozmej do you want to merge it? it is marked as approved

2025-03-29 19:49 UTC, closed without merging

2025-03-29 19:49 UTC, benaadams commented
Very out of date