Add JwtSecret to JsonRpcClient
NethermindEth/nethermind pull request #4429
Opened 2022-08-16 15:06 UTC by smartprogrammer93

Add JwtSecret to JsonRpcClient in the tests

2022-08-16 15:18 UTC, LukaszRozmej commented on src/Nethermind/Nethermind.Overseer.Test/JsonRpc/JsonRpcClient.cs
> +
`Bytes.FromHexString` ?

2022-08-16 15:21 UTC, smartprogrammer93 commented on src/Nethermind/Nethermind.Overseer.Test/JsonRpc/JsonRpcClient.cs
> +
just copy pasted from here
https://github.com/NethermindEth/nethermind/blob/d1bed2f39891e41bba8a79acaf1872d505112644/src/Nethermind/Nethermind.Core/Authentication/MicrosoftJwtAuthentication.cs

2022-08-17 00:35 UTC, smartprogrammer93 commented on src/Nethermind/Nethermind.Overseer.Test/JsonRpc/JsonRpcClient.cs
> +
Applied suggestion

2022-08-17 12:31 UTC, MarekM25 requested changes
The goal of this test was supposed to work without JWT on non-auth port. I don't want to modify JsonRpcClient just because of that. I think we can close this PR

2022-08-17 14:59 UTC, smartprogrammer93 commented
Closing per request

2022-08-17 14:59 UTC, closed without merging