Fix dispose db race condition
NethermindEth/nethermind pull request #4544
Opened 2022-09-08 14:38 UTC by LukaszRozmej

## Changes:
- Fix dispose db race condition

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Other (please describe): 

## Testing
**Requires testing**

- [x] Yes
- [ ] No

**In case you checked yes, did you write tests??**

- [x] Yes
- [ ] No

2022-09-08 16:22 UTC, rubo requested changes

2022-09-08 16:22 UTC, rubo commented on src/Nethermind/Nethermind.Db.Rocks/DbOnTheRocks.cs
> +    private int _isDisposed;
Could we please have `_isDisposed` renamed to `_disposalFlag` or similar? Otherwise, that's a bit misleading as it's no longer a boolean.

2022-09-09 15:15 UTC, rubo approved these changes

2022-10-03 07:15 UTC, LukaszRozmej commented
Move to interlocked didn't actually help

2022-10-03 07:32 UTC, asdacap commented
Gonna merge this?

2022-10-04 11:47 UTC, closed without merging