Ensure scrypt does not fail
NethermindEth/nethermind pull request #4554
Opened 2022-09-11 09:24 UTC by flcl42

File key store fails when Scrypt is used and parameters high enough to cause stack overflow are passed

## Changes:
- Make Scrypt more stable

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Other (please describe): 

## Testing
**Requires testing**

- [x] Yes
- [ ] No

**In case you checked yes, did you write tests??**

- [ ] Yes
- [x] No (enough tests exist)

2022-09-23 17:30 UTC, MarekM25 requested changes
No unit tests?
Was it reported by user?

2022-09-23 17:40 UTC, flcl42 commented
@MarekM25 it's reproducible with an existing unit test on Ubuntu, breaks some tests, @kamilchodola added them after my fix.
No report by a user, may be because there are alternatives to scrypt to switch to if it does not work
@kamilchodola btw haven't you already merge it as part of other branch?

2022-09-23 18:14 UTC, MarekM25 commented
> @MarekM25 it's reproducible with an existing unit test on Ubuntu, breaks some tests, @kamilchodola added them after my fix. No report by a user, may be because there are alternatives to scrypt to switch to if it does not work @kamilchodola btw haven't you already merge it as part of other branch?

okay, so if @kamilchodola is okay, we can include it ;)

2022-09-24 19:32 UTC, kamilchodola commented
@MarekM25 It was in existing test - but it was never included in our test pipeline so that's why it never came.
I believe that if we had a test for that and it was failing and this is fixing it then it is better than before for sure. No other test is affected by that change.

2022-09-24 19:32 UTC, kamilchodola commented
I'd go with merging

2022-09-24 19:32 UTC, kamilchodola approved these changes

2022-09-25 19:33 UTC, kamilchodola approved these changes

2022-09-25 19:58 UTC, MarekM25 approved these changes

2022-09-25 20:42 UTC, merged