Light client
NethermindEth/nethermind pull request #4755
Opened 2022-10-12 15:52 UTC by deffrian

Fixes | Closes | Resolves #

> Anything marked as optional that you didn't need to fill in, please remove it from the PR description. Choose one of the keywords above to refer to the issue this PR solves, followed by the issue number (e.g Fixes # 666). If there is no issue, remove the line. Remove this note after reading.

## Changes:
-

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Other (please describe): 

## Testing
**Requires testing**

- [ x ] Yes
- [ ] No

**In case you checked yes, did you write tests??**

- [ ] Yes
- [ x ] No

**Comments about testing , should you have some** (optional)

## Further comments (optional)

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

2022-10-13 11:20 UTC, LukaszRozmej commented
Why is this a PR?

2022-10-13 11:42 UTC, deffrian commented
> Why is this a PR?

It's draft

2022-10-18 17:15 UTC, LukaszRozmej commented
> > Why is this a PR?
> 
> It's draft, just for testing

No need to be a PR and cause confusion then

2022-10-27 13:40 UTC, MarekM25 commented on src/Nethermind/Nethermind.Blockchain/Synchronization/ISyncConfig.cs
> +        public bool NoValidatorLightClient { get; set; }
don't use LightClient for this

2023-01-03 10:09 UTC, MarekM25 requested changes
No tests

2023-02-23 13:21 UTC, MarekM25 approved these changes

2023-02-23 15:13 UTC, merged

2023-03-03 02:25 UTC, benaadams commented
@deffrian is this working correctly or am I using wrong setting? 🤔

<img width="554" alt="image" src="https://user-images.githubusercontent.com/1142958/222615630-7bf56690-61ac-43db-bdb2-1484e4f05182.png">


<img width="407" alt="image" src="https://user-images.githubusercontent.com/1142958/222614986-e7d53ab7-fa28-43ea-8196-798b9eafbdd6.png">

2023-03-03 03:57 UTC, deffrian commented
@benaadams, you should also disable old bodies/receipts `Sync.Download[Bodies/Receipts]InFastSync=false`

2023-03-03 04:06 UTC, benaadams commented
> @benaadams, you should also disable old bodies/receipts `Sync.Download[Bodies/Receipts]InFastSync=false`

Perfect, works like a dream 👍