Switching from UtcNow to local PayloadPreparationService Stopwatch to fix #4666
NethermindEth/nethermind pull request #4798
Opened 2022-10-21 16:43 UTC by OlegJakushkin

Now using Stopwatch [independent](https://stackoverflow.com/a/12509159/1973207) of system Date time settings.

Resolves #4666

## Changes:
- Switched from DateTimeOffset bound to UtcNow to a single Stopwatch bound to the PayloadPreparationService
- Updated, relevant use cases

## Types of changes
Introduced the use of a Stopwatch to in PayloadPreparationService instead of UtcNow as @LukaszRozmej suggested. No UtcNow passing is needed for it now.

As suggested in #4666 approach to utilize N best blocks was not required and was not employed due to heavy dependency on TimeSpans of surrounding code.

What types of changes does your code introduce?

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Other (please describe): 

## Testing
**Requires testing**
related to block creation.

- [x] Yes
- [ ] No

**In case you checked yes, did you write tests??**
No new tests were created in this PR, as old code coverage is relevant.
- [ ] Yes
- [x] No

2022-10-21 16:43 UTC, OlegJakushkin commented
Currently under block creation testing with Angkor team.

2022-10-25 12:24 UTC, LukaszRozmej reviewed
So we are saving and measuring time intervals from start of the node now? So to get time how much improvement would take it would be `_stopwatch.Elapsed - startTimeStamp`? I think this is correct, though my original idea is to have 1 stopwatch per chain and measuring that elapsed from start of the first improvement in the chain. Not sure if it would be easier to read? Maybe either way we should add a bit of comments?

2022-10-25 12:48 UTC, LukaszRozmej requested changes
One more thing, would be good to add a test that would fail with the previous attempt, but work with this one.

2022-10-26 14:58 UTC, OlegJakushkin commented
Added a test that would fail with the current (master) implementation due to `UtcNow` use
Failure example:
![image](https://user-images.githubusercontent.com/2915361/198059935-b7655c30-d5fe-4bf2-9a6d-91f9dc7f0f9b.png)
Now it is green. 

Note: using MS Fake Stubs, you will need to update CI build pipeline or force-add .dll resource to the repo (which is probably a bad idea). 

Started implementing a test that would fail under my previous PR.

2022-10-26 15:26 UTC, OlegJakushkin commented
CI can not use MS fakes - fails with ` Failed to resolve profiler path from COR_PROFILER_PATH and COR_PROFILER environment variables.`, will guard or remove them.

2022-10-30 02:45 UTC, OlegJakushkin commented
@LukaszRozmej added payloads cleanup test

2025-01-14 07:54 UTC, closed without merging