Reduce number of reads from AccountState inside TxPool::SubmitTx
NethermindEth/nethermind pull request #4820
Opened 2022-10-26 14:16 UTC by deffrian

Fixes | Closes | Resolves #

## Changes:
- First filter that reads SenderAccount from state will save a copy of this data inside new struct: TxFilteringState. If any other filter needs account data it will read it from TxFilteringState. So we read account data only once.

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Other (please describe): 

## Testing
**Requires testing**

- [ x ] Yes
- [ ] No

**In case you checked yes, did you write tests??**

- [ ] Yes
- [ x ] No

2022-10-26 21:52 UTC, LukaszRozmej requested changes
I like the idea with some caveat, lets make this `TxFilteringState` be responsible for this account management like:

```
public struct TxFilteringState
{
    public Account SenderAccount { get { return _account ?? (_account = _accounts.GetAccount(_senderAddress)); } }
}
```

So now we can have this as lazy initialized while dropping this logic from filters.

2022-10-27 12:03 UTC, deffrian commented on src/Nethermind/Nethermind.TxPool/TxFilteringState.cs
> +}
This is for the future. Maybe we will add something else to this structure

2022-10-31 14:16 UTC, LukaszRozmej approved these changes

2022-10-31 15:05 UTC, marcindsobczak approved these changes

2022-11-11 10:59 UTC, merged