Add EIP-5920
NethermindEth/nethermind pull request #5166
Opened 2023-01-18 01:18 UTC by Pandapip1

## Changes

- Adds support for [EIP-5920](https://eips.ethereum.org/EIPS/eip-5920)

## Types of changes

#### What types of changes does your code introduce?

- [ ] Bugfix (a non-breaking change that fixes an issue)
- [x] New feature (a non-breaking change that adds functionality)
- [ ] Breaking change (a fix or a feature that would cause existing functionality not to work as expected)
- [ ] Documentation update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional or API changes)
- [ ] Build-related changes
- [ ] Other: _description_ 

## Testing

#### Requires testing

- [x] Yes
- [ ] No

#### If yes, did you write tests?

- [ ] Yes
- [x] No

#### Notes on testing

Have not written tests. I will be writing tests, and this PR will remain a draft until I have written them.

2023-01-18 01:20 UTC, Pandapip1 commented
I'm waiting for the checks to run to see what code styling things need fixing and what build errors I've introduced.

2023-02-10 07:55 UTC, LukaszRozmej requested changes
Looks good, lacks any tests though

2023-02-11 18:55 UTC, Pandapip1 commented
> Looks good, lacks any tests though

Will definitely write those. Somehow this PR fell off my to do list.

2023-02-12 19:09 UTC, Pandapip1 commented
Added tests, but I'm not sure the tests work.

2023-02-13 11:13 UTC, Scooletz commented
Converting to `draft` for a book keeping purposes.

2023-02-13 20:16 UTC, Pandapip1 commented
@Scooletz mind running the tests?

2023-02-16 07:37 UTC, Scooletz commented
@LukaszRozmej could you help with running the tests?

2023-02-16 08:30 UTC, LukaszRozmej commented on src/Nethermind/Nethermind.Specs/Forks/17_Cancun.cs
> +            IsEip5920Enabled = true;
Eip5920 is not yet confirmed to be in cancun, 4844 is.

2023-02-17 02:07 UTC, Pandapip1 commented
There are some unrelated issues related to EIP-4844 that are causing some tasks to fail.

2023-02-20 13:32 UTC, Pandapip1 commented
@LukaszRomej mind re-approving the workflows?

2023-02-22 22:44 UTC, Pandapip1 commented
I'm going to need some help. I have no idea how to `Execute` in the context of a specific account.

2024-03-11 22:58 UTC, closed without merging