Replace FromHexString + cleanuo
NethermindEth/nethermind pull request #5213
Opened 2023-01-26 10:11 UTC by kamilchodola

## Changes

- Found out a possible builtin function which in tests is almost 2 times faster than current implementation.
For hex: `7b1d3b8a7b9e9e1a7a8c8d57e7a7a6f1c7b1d3b8a7b9e9e1a7a8c8d57e7a7a6f2` results are like below:
<img width="291" alt="image" src="https://user-images.githubusercontent.com/43241881/214803610-07acd222-90d3-4e4f-9a37-67d89b180197.png">
- Additionally browsed through a codebase, found unused implementation which does almost the same + adjusted one in Core2 project.

## Types of changes

#### What types of changes does your code introduce?

- [ ] Bugfix (a non-breaking change that fixes an issue)
- [ ] New feature (a non-breaking change that adds functionality)
- [ ] Breaking change (a change that causes existing functionality not to work as expected)
- [X] Optimization
- [ ] Refactoring
- [ ] Documentation update
- [ ] Build-related changes
- [ ] Other: _Description_

## Testing

#### Requires testing

- [X] Yes
- [ ] No

#### If yes, did you write tests?

Existing one seems to cover the case but revised them once more.
- [X] Yes
- [ ] No

2023-01-26 13:21 UTC, rubo commented
This comes down to replacing the current implementation with `Convert.FromHexString`. If .NET's own one is faster (would like to see the benchmarking code), it's worth replacing with that, of course. Before that, this code needs some revision, indeed.

Better to revert changes in `src/Nethermind/Nethermind.Core2.Abstractions/Bytes.cs`. No longer used.

2023-01-27 09:15 UTC, kamilchodola commented
<img width="675" alt="image" src="https://user-images.githubusercontent.com/43241881/215050126-8ae41ae0-8402-4698-b667-951d1ccc7734.png">
Recent checks with memory allocation included.
Checked for responses for `0x`, `odd` and `even` numbers of chars exactly the same way.

Waiting for unit tests since one seems to be working weird and to be checked if it works fine now on VMs.
@tkstanczak @rubo @kkokosa @damian-orzechowski @LukaszRozmej

2023-01-27 09:16 UTC, kamilchodola commented
Need to still review Unit Tests since more are failing.

2023-01-27 09:19 UTC, kkokosa reviewed
Very nice! Obviously, requires pretty good test coverage to not introduce regression (lower case, upper case, mixed case coming to my mind).

But from optimization point of view, I'd benchmark all four possible combinations of inputs - hex string starting with `0x` or not, hex string length % 2 or not.

2023-01-27 11:15 UTC, kamilchodola commented
Tests are green - working on full benchmarks list

2023-01-30 10:05 UTC, LukaszRozmej requested changes
Please provide benchmarks too to our Benchmarking solution.

Marking @benaadams as he was the one optimizing this in first place.

2023-01-30 10:05 UTC, LukaszRozmej commented on src/Nethermind/Nethermind.Core/Extensions/Bytes.cs
> +                hexString = hexString.Insert(span, "0");
big allocation for odd length strings that we can avoid

2023-01-30 10:05 UTC, LukaszRozmej commented on src/Nethermind/Nethermind.Core2.Abstractions/Bytes.cs
> +                hexString = hexString.Insert(span, "0");
same here

2023-02-01 12:21 UTC, kamilchodola commented
Result for my previous version using benchmarks:
![image](https://user-images.githubusercontent.com/43241881/216041089-71767622-2445-4acb-afcb-5fae691fb032.png)

Will now test a fixed version by Łukasz

2023-02-01 12:38 UTC, kamilchodola commented
@LukaszRozmej 
Your fix make it stable in terms of memory alloc (same results as for previous version).
Execution time is almost two times faster each time so can see improvement in there.

<img width="1218" alt="image" src="https://user-images.githubusercontent.com/43241881/216044473-6c36e37b-3f10-45e9-b234-d1fe1860c943.png">

4 scenarios for each so with or without "0x" and odd/even.

@benaadams @tkstanczak @kkokosa

2023-02-02 12:26 UTC, LukaszRozmej commented
Tested changes to `ToHexString` and there is no difference between the implementations - looking at them they are the same

2023-02-07 10:57 UTC, kamilchodola commented
Tests on final version:
<img width="600" alt="image" src="https://user-images.githubusercontent.com/43241881/217226334-ae183506-8f5a-4168-838a-b12d8da962ba.png">

@LukaszRozmej I guess we can merge since all tests are passing and benchmarks show nice improvement.

2023-02-09 10:28 UTC, LukaszRozmej approved these changes

2023-02-09 12:12 UTC, merged