TraceStore - Check depth when serializing
NethermindEth/nethermind pull request #5344
Opened 2023-02-27 12:35 UTC by LukaszRozmej

## Changes

- Checks graph depth before serialization

## Types of changes

#### What types of changes does your code introduce?

- [x] Bugfix (a non-breaking change that fixes an issue)
- [ ] New feature (a non-breaking change that adds functionality)
- [ ] Breaking change (a change that causes existing functionality not to work as expected)
- [ ] Optimization
- [ ] Refactoring
- [ ] Documentation update
- [ ] Build-related changes
- [ ] Other: _Description_

2023-02-28 13:45 UTC, Scooletz commented
Not sure how deep can be the trace and how big overhead is iterating over it. One could provide a limiting `JsonWriter` that would throw when `Top` is bigger than max (or omit for example).

https://github.com/JamesNK/Newtonsoft.Json/blob/57025815e564d36821acf778e2c00d02225aab35/Src/Newtonsoft.Json/JsonWriter.cs#L144

This would iterate only once but could take a bit more on big ones as it would be discarding the already written stuff.

2023-03-03 14:30 UTC, benaadams approved these changes

2023-03-03 14:39 UTC, smartprogrammer93 approved these changes

2023-03-03 14:42 UTC, Scooletz requested changes
a minor

2023-03-03 14:59 UTC, LukaszRozmej commented on src/Nethermind/Nethermind.JsonRpc.TraceStore/ParityLikeTraceSerializer.cs
> +    private void CheckDepth(ParityTraceAction action, int depth)
would have to pass `_maxDepth`

2023-03-03 14:59 UTC, merged