Fix exception in CleanupOldPayloads from concurrent use of List
NethermindEth/nethermind pull request #5385
Opened 2023-03-07 09:59 UTC by benaadams

## Changes

- If blocks suggested too fast new blocks can be added to the clean up list while it is being enumerated causing an enumeration exception to be thrown. Remove from `ConcurrentDictionary` directly, no need for the second list

## Types of changes

#### What types of changes does your code introduce?

- [x] Bugfix (a non-breaking change that fixes an issue)
- [ ] New feature (a non-breaking change that adds functionality)
- [ ] Breaking change (a change that causes existing functionality not to work as expected)
- [ ] Optimization
- [ ] Refactoring
- [ ] Documentation update
- [ ] Build-related changes
- [ ] Other: _Description_

## Testing

#### Requires testing

- [ ] Yes
- [x] No

#### If yes, did you write tests?

- [ ] Yes
- [x] No

#### Notes on testing

_Optional. Remove if not applicable._

## Remarks

_Optional. Remove if not applicable._

2023-03-07 10:59 UTC, MarekM25 requested changes
Pls, try to write unit test that reproduce the scenario

2023-03-08 16:54 UTC, benaadams commented
> Pls, try to write an unit test that reproduces the scenario

Not sure is easy as need to mess with the timer and then have 2 run concurrently. 

Fix its to remove the type that is throwing as can just remove from ConcurrentDictionary directly while enumerating; don't need to store all the changes in a second type and then iterate that to get the keys from the dictionary. Is an unnecessary step entirely

2023-03-08 21:23 UTC, MarekM25 commented
> > Pls, try to write an unit test that reproduces the scenario
> 
> Not sure is easy as need to mess with the timer and then have 2 run concurrently.
> 
> Fix its to remove the type that is throwing as can just remove from ConcurrentDictionary directly while enumerating; don't need to store all the changes in a second type and then iterate that to get the keys from the dictionary. Is an unnecessary step entirely

Agreed and it is covered by our bad block fuzzing test.

2023-03-08 21:23 UTC, MarekM25 approved these changes

2023-03-09 07:38 UTC, merged