SetTDRpcCall
NethermindEth/nethermind pull request #5439
Opened 2023-03-16 11:10 UTC by deffrian

Fixes Closes Resolves #

#5341 

## Changes

- Adds new rpc call to manually set td for block

## Types of changes

#### What types of changes does your code introduce?

- [ ] Bugfix (a non-breaking change that fixes an issue)
- [x] New feature (a non-breaking change that adds functionality)
- [ ] Breaking change (a change that causes existing functionality not to work as expected)
- [ ] Optimization
- [ ] Refactoring
- [ ] Documentation update
- [ ] Build-related changes
- [ ] Other: _Description_

## Testing

#### Requires testing

- [ ] Yes
- [x] No

2023-03-16 12:26 UTC, MarekM25 requested changes
I think if it is really needed we should write the FixTd process with block numbers (from and to) as an argument (check FixBlooms etc.) but not sure if it is the root cause of the problem

2023-03-27 02:20 UTC, abcfy2 commented
And update about this PR ? Will this PR be merged ?

2023-03-31 17:33 UTC, deffrian commented
@abcfy2 Most probably will be merged next week. After that we can make custom docker image for you. Or you can wait until next release

2023-04-01 13:09 UTC, abcfy2 commented
Thanks. But I use Ubuntu ppa for deployment. So I have to wait for next release.

Thanks all the same.

2023-04-06 07:42 UTC, damian-orzechowski commented on src/Nethermind/Nethermind.Init/Steps/Migrations/TotalDifficultyFixMigration.cs
> +        IBlockTree blockTree = _api.BlockTree ?? throw new ArgumentNullException(nameof(_api.BlockTree));
If migration is only using BlockTree and ChainLevelInfoHistory, it could accept these interfaces in constructor and perform argument check earlier.

2023-04-06 07:47 UTC, damian-orzechowski commented on src/Nethermind/Nethermind.Init/Steps/Migrations/TotalDifficultyFixMigration.cs
> +            UInt256 actualTd = currentLevel.BlockInfos[0].TotalDifficulty;
Just a question - is this possible to have different TD in block info at any other index?

2023-04-12 12:28 UTC, MarekM25 approved these changes

2023-04-12 23:39 UTC, merged