BuilderBlockValidation implementation
NethermindEth/nethermind pull request #5540
Opened 2023-04-05 00:51 UTC by smartprogrammer93

Resolves #5523

## Changes

- introduce new RPC method called `mev_validateBuilderSubmissionV2`

## Types of changes

#### What types of changes does your code introduce?

- [ ] Bugfix (a non-breaking change that fixes an issue)
- [x] New feature (a non-breaking change that adds functionality)
- [ ] Breaking change (a change that causes existing functionality not to work as expected)
- [ ] Optimization
- [ ] Refactoring
- [ ] Documentation update
- [ ] Build-related changes
- [ ] Other: _Description_

## Testing

#### Requires testing

- [x] Yes
- [ ] No

#### If yes, did you write tests?

- [ ] Yes
- [x] No

#### Notes on testing

do let me know if need to write tests for this.

2023-04-11 09:52 UTC, LukaszRozmej requested changes

2023-04-11 09:52 UTC, LukaszRozmej commented on src/Nethermind/Nethermind.Consensus/IGasLimitCalculator.cs
> +        long GetGasLimit(BlockHeader parentHeader, long? targetGasLimit);
I think there should be only one of these methods. Make targetGasLimit `null` by default.

2023-04-11 09:52 UTC, LukaszRozmej commented on src/Nethermind/Nethermind.Mev/Execution/BlockValidationService.cs
> +    public void ValidateBuilderSubmission(BuilderBlockValidationRequest request, bool v2 = false)
not really a fan how versioning is handled.

2023-04-11 09:52 UTC, LukaszRozmej commented on src/Nethermind/Nethermind.Mev/Execution/BlockValidationService.cs
> +        }
Would consider moving basic validation to RPC module.

2023-04-11 09:52 UTC, LukaszRozmej commented on src/Nethermind/Nethermind.Mev/Execution/BlockValidationService.cs
> +            throw new InvalidOperationException($"Block simulation failed. Parent Block StateRoot was null");
Is this possible?

2023-04-11 09:52 UTC, LukaszRozmej commented on src/Nethermind/Nethermind.Mev/MevPlugin.cs
> +                    getFromApi.StateProvider!,
You cannot use main state and main transaction processor here. You need to use ReadOnlyTxProcessingEnvironment like with any other RPC.

2023-04-11 09:52 UTC, LukaszRozmej commented on src/Nethermind/Nethermind.Mev/Execution/BlockValidationService.cs
> +        Block[] processed = _blockProcessor.Process(parentBlock.StateRoot, blocks, ProcessingOptions.ReadOnlyChain & ProcessingOptions.DoNotUpdateHead, tracer);
this will modify main state - will cause errors

2025-03-29 20:00 UTC, benaadams commented
Very out of date

2025-03-29 20:00 UTC, closed without merging