Rename SHA3 opcode to KECCAK256
NethermindEth/nethermind pull request #5929
Opened 2023-07-13 15:57 UTC by Demuirgos

Fixes Closes Resolves #

_Please choose one of the keywords above to refer to the issue this PR solves followed by the issue number (e.g. Fixes #000). If no issue number, remove the line. Also, remove everything marked optional that is not applicable. Remove this note after reading._

## Changes

- Align with other clients with regards to opcode 0x20 naming : SHA3 -> KECCAK256

## Types of changes

#### What types of changes does your code introduce?

- [ ] Bugfix (a non-breaking change that fixes an issue)
- [ ] New feature (a non-breaking change that adds functionality)
- [ ] Breaking change (a change that causes existing functionality not to work as expected)
- [ ] Optimization
- [x] Refactoring
- [ ] Documentation update
- [ ] Build-related changes
- [ ] Other: _Description_

## Testing

#### Requires testing

- [ ] Yes
- [x] No

#### If yes, did you write tests?

- [ ] Yes
- [x] No

#### Notes on testing

_Optional. Remove if not applicable._

## Documentation

#### Requires documentation update

- [ ] Yes
- [x] No

_If yes, link the PR to the docs update or the issue with the details labeled `docs`. Remove if not applicable._

#### Requires explanation in Release Notes

- [ ] Yes
- [x] No

_If yes, fill in the details here. Remove if not applicable._

## Remarks

_Optional. Remove if not applicable._

2023-07-13 15:59 UTC, smartprogrammer93 approved these changes
As discussed this reflects the execution spec and how other clients name the opcode

2023-07-13 17:41 UTC, rubo requested changes

2023-07-13 17:41 UTC, rubo commented on src/Nethermind/Nethermind.Evm.Test/Sha3Tests.cs
> +                .Op(Instruction.KECCAK256)
Rename `Sha3Tests` to `Keccak256Tests`

2023-07-13 17:58 UTC, benaadams approved these changes

2023-07-13 18:14 UTC, LukaszRozmej commented
Not sure but the reason for the naming might have been compatibility with `Parity`/`OpenEthereum`. maybe this will break something in traces from `trace` module?

2023-07-13 18:26 UTC, rubo commented
> maybe this will break something in traces from `trace` module?

@LukaszRozmej If any old-style tracing compatibility is broken, then it should be addressed in that particular tracer itself. This should've been renamed long ago, the choice of `SHA3` was just historical and not for compatibility reasons. This already has already been discussed a year ago.

2023-07-13 18:43 UTC, rubo commented
@Demuirgos `Update_known_chain_sizes` test fails for Goerli. Not sure what's wrong there.

2023-07-14 11:22 UTC, MarekM25 approved these changes

2023-07-14 11:26 UTC, rubo approved these changes

2023-07-14 11:28 UTC, merged