Merge 1.20.1 into master branch
NethermindEth/nethermind pull request #5975
Opened 2023-07-31 14:03 UTC by kamilchodola

Fixes Closes Resolves #

There were some fixes in 1.20.1 which may not be yet included in master branch so we need to merge them back.

## Types of changes

#### What types of changes does your code introduce?

- [X] Bugfix (a non-breaking change that fixes an issue)
- [ ] New feature (a non-breaking change that adds functionality)
- [ ] Breaking change (a change that causes existing functionality not to work as expected)
- [ ] Optimization
- [ ] Refactoring
- [ ] Documentation update
- [ ] Build-related changes
- [ ] Other: _Description_

## Testing

#### Requires testing

- [ ] Yes
- [X] No

#### If yes, did you write tests?

- [ ] Yes
- [X] No

#### Notes on testing

_Optional. Remove if not applicable._

## Documentation

#### Requires documentation update

- [ ] Yes
- [X] No

_If yes, link the PR to the docs update or the issue with the details labeled `docs`. Remove if not applicable._

#### Requires explanation in Release Notes

- [ ] Yes
- [X] No

_If yes, fill in the details here. Remove if not applicable._

## Remarks

_Optional. Remove if not applicable._

2023-07-31 14:04 UTC, marcindsobczak approved these changes

2023-07-31 14:07 UTC, benaadams approved these changes

2023-07-31 14:14 UTC, rubo requested changes

2023-07-31 14:14 UTC, rubo commented on src/Nethermind/nuget.config
> +    <add key="nugettest.org" value="https://apiint.nugettest.org/v3/index.json" />
This should not be merged. I'll prepare what's needed.

2023-07-31 14:38 UTC, rubo commented on src/Nethermind/nuget.config
> +    <add key="nugettest.org" value="https://apiint.nugettest.org/v3/index.json" />
@kamilchodola [Here](https://github.com/NethermindEth/nethermind/pull/5976) you go

2023-07-31 15:30 UTC, rubo approved these changes

2023-07-31 15:51 UTC, marcindsobczak approved these changes

2023-08-01 08:01 UTC, kamilchodola commented
@rubo Wasn't that a fix for Homebrew installation?

2023-08-01 08:03 UTC, merged