Fix `eth_syncing` in young chains
NethermindEth/nethermind pull request #6181
Opened 2023-10-11 15:12 UTC by emlautarom1

Fixes #6153

## Changes

- Fix edge case where `eth_syncing` never returned false given that receipts were never downloaded.

## Types of changes

#### What types of changes does your code introduce?

- [x] Bugfix (a non-breaking change that fixes an issue)
- [ ] New feature (a non-breaking change that adds functionality)
- [ ] Breaking change (a change that causes existing functionality not to work as expected)
- [ ] Optimization
- [ ] Refactoring
- [ ] Documentation update
- [ ] Build-related changes
- [ ] Other: _Description_

## Testing

#### Requires testing

- [x] Yes
- [ ] No

#### If yes, did you write tests?

- [ ] Yes
- [x] No

#### Notes on testing

Tested on a VM running Holesky with the current default config (https://github.com/NethermindEth/nethermind/blob/9c40c81de03a3f9d4f4f5e10cf93eef767f71071/src/Nethermind/Nethermind.Runner/configs/holesky.cfg) and with `PivotNumber: 100`

## Documentation

#### Requires documentation update

- [ ] Yes
- [x] No

#### Requires explanation in Release Notes

- [ ] Yes
- [x] No

## Remarks

The justification as to why this fixes the issue is complex and more details will be provided as part of the discussion on this PR.

2023-10-12 11:42 UTC, LukaszRozmej commented on src/Nethermind/Nethermind.Facade/Eth/EthSyncingInfo.cs
> +            if (_syncConfig.FastSync && _syncConfig.PivotNumberParsed != 0)
Can we refactor to something more readable? So name the conditions better and where we can't add comments.

2023-10-12 20:33 UTC, MarekM25 requested changes
It would be great to add at least one unit tests + I agree with Łukasz about naming :)

2023-10-13 19:11 UTC, emlautarom1 commented on src/Nethermind/Nethermind.Facade/Eth/EthSyncingInfo.cs
> +            if (_syncConfig.FastSync && _syncConfig.PivotNumberParsed != 0)
Done: added explanation comment and introduced intermediate variables for better clarity.

2023-10-26 21:09 UTC, LukaszRozmej approved these changes

2023-10-30 13:18 UTC, MarekM25 approved these changes

2023-10-30 13:20 UTC, merged