Fix Antithesis NullPointerException in Evm
NethermindEth/nethermind pull request #6191
Opened 2023-10-13 11:35 UTC by Demuirgos

Fixes Closes Resolves #

_Please choose one of the keywords above to refer to the issue this PR solves followed by the issue number (e.g. Fixes #000). If no issue number, remove the line. Also, remove everything marked optional that is not applicable. Remove this note after reading._

## Changes

- Fix Antithesis NullException 

## Types of changes

#### What types of changes does your code introduce?

- [x] Bugfix (a non-breaking change that fixes an issue)
- [ ] New feature (a non-breaking change that adds functionality)
- [ ] Breaking change (a change that causes existing functionality not to work as expected)
- [ ] Optimization
- [ ] Refactoring
- [ ] Documentation update
- [ ] Build-related changes
- [ ] Other: _Description_

## Testing

#### Requires testing

- [x] Yes
- [ ] No

#### If yes, did you write tests?

- [x] Yes
- [ ] No

#### Notes on testing

_Optional. Remove if not applicable._

## Documentation

#### Requires documentation update

- [ ] Yes
- [x] No

_If yes, link the PR to the docs update or the issue with the details labeled `docs`. Remove if not applicable._

#### Requires explanation in Release Notes

- [ ] Yes
- [x] No

_If yes, fill in the details here. Remove if not applicable._

## Remarks

_Optional. Remove if not applicable._

2023-10-13 12:15 UTC, smartprogrammer93 approved these changes

2023-10-13 12:26 UTC, smartprogrammer93 commented on src/Nethermind/Nethermind.Evm/TransactionProcessing/TransactionProcessor.cs
> +                    return false;
not a spec. resolving this:
https://hackmd.io/@opBRCgEeSP6XKr0nO99rbQ/Sy8I87wyp#Nethermind

2023-10-13 12:32 UTC, LukaszRozmej commented on src/Nethermind/Nethermind.Evm/TransactionProcessing/TransactionProcessor.cs
> +                    return false;
transaction processing is part of consensus - it should have spec, we cannot just do as we please.

2023-10-13 12:34 UTC, smartprogrammer93 commented on src/Nethermind/Nethermind.Evm/TransactionProcessing/TransactionProcessor.cs
> +                    return false;
okay so maybe we can put this validation at JsonRpc level or the blockchain bridge?

2023-10-13 12:34 UTC, smartprogrammer93 commented on src/Nethermind/Nethermind.Evm/TransactionProcessing/TransactionProcessor.cs
> +                    return false;
you are absolutely right, we are failing ethereum tests with this. damn

2023-10-13 12:35 UTC, smartprogrammer93 requested changes
need to move the validation up to JsonRPC level maybe

2023-10-13 16:50 UTC, smartprogrammer93 commented
@LukaszRozmej  we checked geth behavior and copied the same

2023-10-13 16:51 UTC, smartprogrammer93 approved these changes

2023-10-13 23:09 UTC, LukaszRozmej approved these changes

2023-10-14 08:58 UTC, benaadams approved these changes

2023-10-14 09:09 UTC, merged