Feature/more diagnostics bad blocks
NethermindEth/nethermind pull request #6207
Opened 2023-10-19 14:57 UTC by LukaszRozmej

## Changes

- Adds RLP dump option and adds it to default
- Adds extra data to log when block is invalid

## Types of changes

#### What types of changes does your code introduce?

- [ ] Bugfix (a non-breaking change that fixes an issue)
- [x] New feature (a non-breaking change that adds functionality)
- [ ] Breaking change (a change that causes existing functionality not to work as expected)
- [ ] Optimization
- [ ] Refactoring
- [ ] Documentation update
- [ ] Build-related changes
- [ ] Other: _Description_

## Testing

#### Requires testing

- [x] Yes
- [ ] No

#### If yes, did you write tests?

- [ ] Yes
- [x] No

2023-10-20 19:01 UTC, MarekM25 commented
@LukaszRozmej I would consider adding RLP directly to the info log. It would improve the debugging

2023-10-20 19:18 UTC, LukaszRozmej commented
> @LukaszRozmej I would consider adding RLP directly to the info log. It would improve the debugging

But then would it be good to be Info and default? Not sure if we want multiple rlps being logged on bad blocks. Could scare users.

2023-10-21 09:23 UTC, MarekM25 commented
> > @LukaszRozmej I would consider adding RLP directly to the info log. It would improve the debugging
> 
> But then would it be good to be Info and default? Not sure if we want multiple rlps being logged on bad blocks. Could scare users.

What about adding extra dump mode? It would be super useful now

2023-10-21 09:35 UTC, MarekM25 commented on src/Nethermind/Nethermind.Consensus/Validators/BlockValidator.cs
> +            _logger.Error($"- parent beacon block root : expected {suggestedBlock.Header.ParentBeaconBlockRoot}, got {processedBlock.Header.ParentBeaconBlockRoot}");
![Screenshot from 2023-10-21 11-33-27](https://github.com/NethermindEth/nethermind/assets/9356351/f3cf50f2-52f9-4dc4-9bf0-fdc48ebde54e)
line to remove?

2023-10-21 09:35 UTC, MarekM25 commented on src/Nethermind/Nethermind.Blockchain/LogTraceDumper.cs
> +            logger.Info($"Created a Receipts trace of block {blockHash} in file {diagnosticFile.Name}");
"Created a Receipts trace of block" -> "Created a RLP dump of block"

2023-10-22 11:35 UTC, rubo requested changes

2023-10-22 11:35 UTC, rubo commented on src/Nethermind/Nethermind.Blockchain/LogTraceDumper.cs
> +        string fileName = $"block_{blockHash}.txt";
The `.txt` extension is misleading as the file is binary. Let's either remove it or change to `.rlp`:

```suggestion
        string fileName = $"block_{blockHash}.rlp";
```

2023-10-24 13:25 UTC, rubo approved these changes

2023-10-25 12:45 UTC, merged