Add last block hash to exposed metrics
NethermindEth/nethermind pull request #6498
Opened 2024-01-10 16:15 UTC by zguesmi

Resolves #6497 

## Changes

- Add the field `LastBlockHash` to `src/Nethermind/Nethermind.Blockchain/Metrics.cs`

## Types of changes

#### What types of changes does your code introduce?

- [ ] Bugfix (a non-breaking change that fixes an issue)
- [x] **New feature (a non-breaking change that adds functionality)**
- [ ] Breaking change (a change that causes existing functionality not to work as expected)
- [ ] Optimization
- [ ] Refactoring
- [ ] Documentation update
- [ ] Build-related changes
- [ ] Other: _Description_

## Testing

#### Requires testing

- [x] Yes
- [ ] No

#### If yes, did you write tests?

- [ ] Yes
- [x] No

#### Notes on testing

I could not find where to add them.

## Documentation

#### Requires documentation update

- [x] Yes
- [ ] No

I can create the PR if this request is accepted.

#### Requires explanation in Release Notes

- [x] Yes
- [ ] No

Add an entry to the release notes:
- Added last block hash to exposed metrics

## Remarks

2024-01-12 22:41 UTC, benaadams commented
I don't think Grafana likes string metrics; however Exemplars might be the way to go? https://grafana.com/docs/grafana/latest/fundamentals/exemplars/ (or for .NET https://github.com/prometheus-net/prometheus-net?tab=readme-ov-file#exemplars)

Perhaps on the blockchainheight metric?

2024-01-13 03:45 UTC, benaadams requested changes
I don't think Grafana likes string metrics; however Exemplars might be the way to go? https://grafana.com/docs/grafana/latest/fundamentals/exemplars/ (or for .NET https://github.com/prometheus-net/prometheus-net?tab=readme-ov-file#exemplars)

Perhaps on the blockchainheight metric?

2024-01-22 11:20 UTC, zguesmi commented
Thank you @benaadams for you suggestion.
Indeed string values are not supported in Prometheus and Grafana. I tried using labels (add a label `block_hash` to the metric `blockchain_height`) but I didn't manage to set it dynamically. I'm afraid we would have the same issue with Exemplars.
The suggestion of @LukaszRozmej was to grab the first 8 bytes of the hash and export it as a number. This should be enough for what I'm trying to achieve here.

2026-04-16 13:26 UTC, svlachakis commented
stale for too long, closing

2026-04-16 13:26 UTC, closed without merging