Cancun spec and config for mainnet
NethermindEth/nethermind pull request #6679
Opened 2024-02-09 12:48 UTC by smartprogrammer93

## Changes

- Cancun spec and config for mainnet

## Types of changes

#### What types of changes does your code introduce?

- [ ] Bugfix (a non-breaking change that fixes an issue)
- [x] New feature (a non-breaking change that adds functionality)
- [ ] Breaking change (a change that causes existing functionality not to work as expected)
- [ ] Optimization
- [ ] Refactoring
- [ ] Documentation update
- [ ] Build-related changes
- [ ] Other: _Description_

## Testing

#### Requires testing

- [x] Yes
- [ ] No

#### If yes, did you write tests?

- [x] Yes
- [ ] No

## Documentation

#### Requires documentation update

- [ ] Yes
- [x] No

_If yes, link the PR to the docs update or the issue with the details labeled `docs`. Remove if not applicable._

#### Requires explanation in Release Notes

- [x] Yes
- [ ] No

Cancun spec and config for mainnet added

2024-02-10 21:05 UTC, LukaszRozmej requested changes

2024-02-10 21:05 UTC, LukaszRozmej commented on src/Nethermind/Nethermind.Runner/configs/mainnet.cfg
> +    "Size": 1024,
Do we need size, why not default?

2024-02-10 21:05 UTC, LukaszRozmej commented on src/Nethermind/Nethermind.Runner/configs/mainnet_archive.cfg
> +    "Size": 1024,
Do we need size, why not default?

2024-02-10 21:05 UTC, LukaszRozmej commented on src/Nethermind/Nethermind.Runner/configs/mainnet.cfg
> +    "BlobsSupport": "StorageWithReorgs"
If we are going to mainnet, I think we should make "StorageWithReorgs" default, and actually set it different only in places where we don't need it.

2024-02-10 21:05 UTC, LukaszRozmej commented on src/Nethermind/Nethermind.Runner.Test/ConfigFilesTests.cs
> +        [TestCase("mainnet", 1024)]
why decrease for mainnet? I think we don't want it

2024-02-11 05:09 UTC, smartprogrammer93 commented
@marcindsobczak what do you think about luk's comments?

2024-02-12 10:04 UTC, marcindsobczak commented on src/Nethermind/Nethermind.Runner/configs/mainnet.cfg
> +    "Size": 1024,
+1, just use default (2048)

2024-02-12 10:19 UTC, marcindsobczak commented
Agree with @LukaszRozmej , we have 2048 as default TxPool size for many years and it works well (we tested 1k, 4k and 8k back then and chose 2k), no need to change it now (especially without benchmarking).

About making `StorageWithReorgs` default - agree as well.
If you @smartprogrammer93 want you can change default value and then adjust every pre-canun config to

```
  "TxPool": {
    "BlobsSupport": "Disabled"
  },
```

But if you want, we can merge it as it is (except 1024 for std TxPool) and I will handle it in separate PR

2024-02-12 10:28 UTC, smartprogrammer93 commented
@marcindsobczak ill address it in this PR. No problem

2024-02-12 12:59 UTC, LukaszRozmej approved these changes

2024-02-12 12:59 UTC, LukaszRozmej commented on src/Nethermind/Nethermind.Runner/configs/AuraTest.cfg
> +  },
We can skip this one

2024-02-12 13:23 UTC, marcindsobczak approved these changes

2024-02-12 15:29 UTC, rubo commented
Given the `TxPool.Size: 1024` for Chiado, don't we need the same for Gnosis?

2024-02-12 15:30 UTC, smartprogrammer93 commented
@rubo i think the idea is testnets usually run on lower spec machines. and that is why we have 1024 for testnets and 2048 for "mainnets"

2024-02-13 08:56 UTC, kamilchodola commented on src/Nethermind/Nethermind.Runner/configs/op-sepolia_archive.cfg
> +    "BlobsSupport": "Disabled"
Is it actually valid that OP stack will have blobs disabled? Will there be some separate release for OP chains to support blobs?

2024-02-13 09:14 UTC, kamilchodola approved these changes

2024-02-13 12:03 UTC, MarekM25 approved these changes
LGTM

2024-02-13 13:40 UTC, merged