Load td for beacon block if possible to help handle multiple fcus sent with no delay
NethermindEth/nethermind pull request #6878
Opened 2024-03-29 09:01 UTC by flcl42

Fixes windows nethermind + lighthouse sync issue

## Changes

- Load td for beacon block if possible

## Types of changes

#### What types of changes does your code introduce?

- [x] Bugfix (a non-breaking change that fixes an issue)
- [ ] New feature (a non-breaking change that adds functionality)
- [ ] Breaking change (a change that causes existing functionality not to work as expected)
- [ ] Optimization
- [ ] Refactoring
- [ ] Documentation update
- [ ] Build-related changes
- [ ] Other: _Description_

## Testing

#### Requires testing

- [x] Yes
- [ ] No

#### If yes, did you write tests?

- [x] Yes
- [ ] No

2024-03-29 19:38 UTC, MarekM25 requested changes
Can we use FinalTotalDifficulty from PosSwitcher? or generally share the logic. There are a few more cases here, not only hardcoded pivot

2024-04-11 07:07 UTC, LukaszRozmej approved these changes

2024-04-11 08:18 UTC, marcindsobczak approved these changes

2024-04-11 13:38 UTC, flcl42 commented
> Can we use FinalTotalDifficulty from PosSwitcher? or generally share the logic. There are a few more cases here, not only hardcoded pivot

Fixed

2024-04-11 14:08 UTC, merged