EIP-7667: Update gas costs
NethermindEth/nethermind pull request #6932
Opened 2024-04-18 12:41 UTC by yerke26

Fixes Closes Resolves #

https://github.com/NethermindEth/nethermind/issues/6924

## Changes

Update gas cost for opcodes and precompiles mentioned in EIP-7667
## Types of changes

#### What types of changes does your code introduce?

- [ ] Bugfix (a non-breaking change that fixes an issue)
- [ ] New feature (a non-breaking change that adds functionality)
- [ ] Breaking change (a change that causes existing functionality not to work as expected)
- [ ] Optimization
- [ ] Refactoring
- [ ] Documentation update
- [ ] Build-related changes
- [ ] Other: _Description_

## Testing

#### Requires testing

- [ ] Yes
- [ ] No

#### If yes, did you write tests?

- [ ] Yes
- [ ] No

#### Notes on testing

_Optional. Remove if not applicable._

## Documentation

#### Requires documentation update

- [ ] Yes
- [ ] No

_If yes, link the PR to the docs update or the issue with the details labeled `docs`. Remove if not applicable._

#### Requires explanation in Release Notes

- [ ] Yes
- [ ] No

_If yes, fill in the details here. Remove if not applicable._

## Remarks

_Optional. Remove if not applicable._

2024-04-18 14:56 UTC, LukaszRozmej requested changes
We can't change cost on historical blocks, this needs to be decided dependent on EIP activation.

2024-04-19 11:48 UTC, LukaszRozmej reviewed
Need to add proper way of parsing/converting from json, but otherwise looks good.

I think BLAKE2 precompile cost is still missing.

2024-04-19 15:01 UTC, tanishqjasoria requested changes
you can refer to changes in `Nethermind.Specs` [here](https://github.com/NethermindEth/nethermind/pull/6925) to understand the changes that are needed for parsing json.

for BLAKE2 gas, update `BLAKE2_GFROUND` cost. 
ref: https://github.com/ethereum/EIPs/blob/master/EIPS/eip-152.md

2024-04-22 13:40 UTC, LukaszRozmej reviewed
Looks good, could use some tests

2024-04-22 13:40 UTC, LukaszRozmej approved these changes, later dismissed

2024-04-23 11:32 UTC, yerke26 commented on src/Nethermind/Nethermind.Evm/VirtualMachine.cs
> +                (long)length * GasCostOf.LogData, ref gasAvailable)) return EvmExceptionType.OutOfGas;
fixed

2024-04-24 07:07 UTC, tanishqjasoria commented on src/Nethermind/Nethermind.Evm/VirtualMachine.cs
> +                (long)length * GasCostOf.LogData, ref gasAvailable)) return EvmExceptionType.OutOfGas;
in the line above also - why are we using `GasCostOf.Log` and not `spec.GetLogDataCost()`

2024-04-24 07:11 UTC, tanishqjasoria requested changes
we need some tests here - you can have a look at Evm.Tests/Eip152Test.cs
it will give you some idea on how to write some tests for this change

2024-04-24 13:35 UTC, LukaszRozmej commented on src/Nethermind/Nethermind.Evm/VirtualMachine.cs
> +                (long)length * GasCostOf.LogData, ref gasAvailable)) return EvmExceptionType.OutOfGas;
@tanishqjasoria  Yes but this is fine, only cost of data changes.

2024-04-25 07:41 UTC, tanishqjasoria requested changes

2024-04-25 07:41 UTC, tanishqjasoria commented on src/Nethermind/Nethermind.Evm.Test/Eip7667Tests.cs
> +        Assert.That(resultEipEnabled.GasSpent - resultEipDisabled.GasSpent, Is.EqualTo(gasDifference));
just have a look at how other test works regarding checking values before and after. implement this similarly. EIP3651Tests can be a good reference for that.

2024-04-25 11:42 UTC, tanishqjasoria approved these changes
LGTM

2024-07-02 11:51 UTC, MarekM25 approved these changes

2026-07-10 02:06 UTC, stdevMac commented
Closing: EIP-7667 was moved to Stagnant status and was never scheduled for a fork; hash-cost repricing is being pursued through the newer Glamsterdam repricing EIPs instead.

2026-07-10 02:06 UTC, closed without merging