Fetch blockHashes from state in Eip-7709,
NethermindEth/nethermind pull request #7140
Opened 2024-06-06 09:34 UTC by yerke26

Fixes Closes Resolves #

_Please choose one of the keywords above to refer to the issue this PR solves followed by the issue number (e.g. Fixes #000). If no issue number, remove the line. Also, remove everything marked optional that is not applicable. Remove this note after reading._

## Changes

- _List the changes_

## Types of changes

#### What types of changes does your code introduce?

- [ ] Bugfix (a non-breaking change that fixes an issue)
- [ ] New feature (a non-breaking change that adds functionality)
- [ ] Breaking change (a change that causes existing functionality not to work as expected)
- [ ] Optimization
- [ ] Refactoring
- [ ] Documentation update
- [ ] Build-related changes
- [ ] Other: _Description_

## Testing

#### Requires testing

- [ ] Yes
- [ ] No

#### If yes, did you write tests?

- [ ] Yes
- [ ] No

#### Notes on testing

_Optional. Remove if not applicable._

## Documentation

#### Requires documentation update

- [ ] Yes
- [ ] No

_If yes, link the PR to the docs update or the issue with the details labeled `docs`. Remove if not applicable._

#### Requires explanation in Release Notes

- [ ] Yes
- [ ] No

_If yes, fill in the details here. Remove if not applicable._

## Remarks

_Optional. Remove if not applicable._

2024-06-06 09:51 UTC, tanishqjasoria commented on src/Nethermind/Nethermind.Blockchain/Blocks/BlockhashStore.cs
> +        Address eip2935Account = spec.Eip2935ContractAddress;
this should not be removed

2024-06-06 09:54 UTC, tanishqjasoria commented
NOTE: though 7709 is included here but the implementation is not complete yet -  we dont charge the appropiate gas as its dependent on verkle. 
Should we keep it or just remove it entirely?
cc: @MarekM25 @LukaszRozmej

2024-06-12 05:32 UTC, tanishqjasoria requested changes

2024-06-12 05:32 UTC, tanishqjasoria commented on src/Nethermind/Nethermind.Evm.Test/Eip2935Tests.cs
>      public void CorrectBlockhashBeingUsed(ulong timestamp, bool eipEnabled)
here eipEnabled=false does not make sense
eip2935 is enabled - just the expectation changed
i think this test can be removed or modify it for using 7709

2024-06-12 05:32 UTC, tanishqjasoria commented on src/Nethermind/Nethermind.Blockchain.Test/BlockhashProviderTests.cs
> +            if (currentHeader.Number > Eip2935Constants.RingBufferSize || spec.IsEip7709Enabled || currentHeader.Number > 256)
this condition does not make sense - i think this should be
`(spec.IsEip7709Enabled && currentHeader.Number > Eip2935Constants.RingBufferSize) || currentHeader.Number > 256`

2024-06-18 05:25 UTC, tanishqjasoria commented on src/Nethermind/Nethermind.Blockchain/Blocks/BlockhashStore.cs
> +        Address eip2935Account = spec.Eip2935ContractAddress;
@yerke26

2024-06-18 05:34 UTC, tanishqjasoria approved these changes

2024-06-21 05:43 UTC, rjnrohit approved these changes

2024-06-24 11:26 UTC, LukaszRozmej approved these changes

2024-06-24 11:38 UTC, merged