ci: remove repository dispatch token usage
NethermindEth/nethermind pull request #7191
Opened 2024-06-17 19:42 UTC by cbermudez97

## Changes

- Remove `REPOSITORY_DISPATCH_TOKEN` usage in Github workflows

## Types of changes

#### What types of changes does your code introduce?

- [ ] Bugfix (a non-breaking change that fixes an issue)
- [ ] New feature (a non-breaking change that adds functionality)
- [ ] Breaking change (a change that causes existing functionality not to work as expected)
- [ ] Optimization
- [ ] Refactoring
- [ ] Documentation update
- [ ] Build-related changes
- [x] Other: Github workflows

2024-06-17 19:45 UTC, rubo requested changes
Please restore the single quotes.

2024-06-18 14:19 UTC, cbermudez97 commented
@rubo noticed some workflows here that use the old token to call to Dappnodes repository. I'm not aware if this is something still in usage. Just to remove as our GH app wont have access to any external repository.

Links:
https://github.com/NethermindEth/nethermind/blob/ci/remove-dispatch-token/.github/workflows/update-dappnode-package.yml

cc @kamilchodola

2024-06-21 13:26 UTC, kamilchodola approved these changes

2024-06-21 13:34 UTC, stdevMac approved these changes

2024-06-21 14:27 UTC, merged

2024-06-21 14:52 UTC, rubo commented
Why was this merged without addressing the requested changes?