Skip eth_getLogs error for NonValidatorNodes
NethermindEth/nethermind pull request #7216
Opened 2024-06-23 23:15 UTC by benaadams

## Changes

- Don't output `Error when handling Id:N, eth_getLogs` for NonValidatorNode as is likely is because they aren't syncing receipts

## Types of changes

#### What types of changes does your code introduce?

- [x] New feature (a non-breaking change that adds functionality)

## Testing

#### Requires testing

- [x] No

2024-06-24 09:05 UTC, LukaszRozmej requested changes
This is not the place to do it. `ResultWrapper` has `IsTemporary` (Might be renamed?) which would translate into `SuppressWarning` thus we could use it directly from `eth_getLogs`

2024-06-24 09:09 UTC, benaadams commented
> This is not the place to do it. `ResultWrapper` has `IsTemporary` (Might be renamed?) which would translate into `SuppressWarning` thus we could use it directly from `eth_getLogs`

Not sure I understand; pass `_syncConfig.NonValidatorNode` into `eth_getLogs` ?

2024-06-24 11:28 UTC, LukaszRozmej commented
> > This is not the place to do it. `ResultWrapper` has `IsTemporary` (Might be renamed?) which would translate into `SuppressWarning` thus we could use it directly from `eth_getLogs`
> 
> Not sure I understand; pass `_syncConfig.NonValidatorNode` into `eth_getLogs` ?

I would pass it into `EthRpcModule`

2025-04-10 21:48 UTC, benaadams commented
This will be resolved post Pectra; don't think is needed anymore

2025-04-10 21:48 UTC, closed without merging