Created one more abstraction between WorldStateManager and WorldState…
NethermindEth/nethermind pull request #7403
Opened 2024-09-08 19:43 UTC by yerke26

… - WorldStateProvider

Fixes Closes Resolves #

_Please choose one of the keywords above to refer to the issue this PR solves followed by the issue number (e.g. Fixes #000). If no issue number, remove the line. Also, remove everything marked optional that is not applicable. Remove this note after reading._

## Changes

- _List the changes_

## Types of changes

#### What types of changes does your code introduce?

- [ ] Bugfix (a non-breaking change that fixes an issue)
- [ ] New feature (a non-breaking change that adds functionality)
- [ ] Breaking change (a change that causes existing functionality not to work as expected)
- [ ] Optimization
- [ ] Refactoring
- [ ] Documentation update
- [ ] Build-related changes
- [ ] Other: _Description_

## Testing

#### Requires testing

- [ ] Yes
- [ ] No

#### If yes, did you write tests?

- [ ] Yes
- [ ] No

#### Notes on testing

_Optional. Remove if not applicable._

## Documentation

#### Requires documentation update

- [ ] Yes
- [ ] No

_If yes, link the PR to the docs update or the issue with the details labeled `docs`. Remove if not applicable._

#### Requires explanation in Release Notes

- [ ] Yes
- [ ] No

_If yes, fill in the details here. Remove if not applicable._

## Remarks

_Optional. Remove if not applicable._

2024-09-09 16:24 UTC, tanishqjasoria requested changes

2024-09-10 06:43 UTC, yerke26 commented on src/Nethermind/Nethermind.State/WorldStateManager.cs
> +    public override IWorldStateProvider WorldStateProvider => worldStateProvider;
renamed

2024-09-10 06:43 UTC, yerke26 commented on src/Nethermind/Nethermind.State/ReadOnlyWorldStateProvider.cs
> +    public virtual void RestoreBranch(Hash256 branchingPointStateRoot) => throw new InvalidOperationException("world state is not supported");
Forgot to remove while refactoring

2024-09-10 22:02 UTC, tanishqjasoria approved these changes

2024-09-10 22:02 UTC, merged