Only write to tree net changes at end of block
NethermindEth/nethermind pull request #7406
Opened 2024-09-09 14:29 UTC by benaadams

Fixes Closes Resolves #

_Please choose one of the keywords above to refer to the issue this PR solves followed by the issue number (e.g. Fixes #000). If no issue number, remove the line. Also, remove everything marked optional that is not applicable. Remove this note after reading._

## Changes

- _List the changes_

## Types of changes

#### What types of changes does your code introduce?

- [ ] Bugfix (a non-breaking change that fixes an issue)
- [ ] New feature (a non-breaking change that adds functionality)
- [ ] Breaking change (a change that causes existing functionality not to work as expected)
- [ ] Optimization
- [ ] Refactoring
- [ ] Documentation update
- [ ] Build-related changes
- [ ] Other: _Description_

## Testing

#### Requires testing

- [ ] Yes
- [ ] No

#### If yes, did you write tests?

- [ ] Yes
- [ ] No

#### Notes on testing

_Optional. Remove if not applicable._

## Documentation

#### Requires documentation update

- [ ] Yes
- [ ] No

_If yes, link the PR to the docs update or the issue with the details labeled `docs`. Remove if not applicable._

#### Requires explanation in Release Notes

- [ ] Yes
- [ ] No

_If yes, fill in the details here. Remove if not applicable._

## Remarks

_Optional. Remove if not applicable._

2025-03-24 09:06 UTC, benaadams commented on src/Nethermind/Nethermind.State.Test/StorageProviderTests.cs
> -        ctx.StateProvider.Commit(Frontier.Instance);
`storageProvider` and `ctx.StateProvider` are the same, so using both is confusing

2025-03-24 09:07 UTC, benaadams commented on src/Nethermind/Nethermind.State.Test/StorageProviderTests.cs
> +        storageProvider.Commit(Frontier.Instance);
Although this is a double commit, so shouldn't do anything; it did help find a bug, so keeping

2025-03-24 09:24 UTC, LukaszRozmej commented
Does it increase throughput?

2025-03-24 09:44 UTC, benaadams commented
> Does it increase throughput?

Yes, a lot of mev front-run + tx + back-run end up with some net zero changes across the block but we merklize the changes when considering each tx individually. Also allows us to parallelize all the storage merklization for the block rather than doing it sequentially for each tx

2025-03-24 09:48 UTC, benaadams commented
> > Does it increase throughput?
> 
> Yes, a lot of mev front-run + tx + back-run end up with some net zero changes across the block but we merklize the changes when considering each tx individually.
> 
> Also allows us to parallelize all the storage merklization for the block rather than doing it sequentially for each tx

e.g. heavy SSTORE blocks have lower impact
![image](https://github.com/user-attachments/assets/70448314-953b-48b0-8be8-83ee429a6b46)

2025-03-24 12:17 UTC, LukaszRozmej reviewed
Looks a bit risky to be honest

2025-03-24 12:28 UTC, Scooletz requested changes
Remarks provided.
The description of this PR states _Often the net changes for state and storage across all the tx in the block is nothing; so skip writing to db when this is the case_, but is it only the case? Isn't it amortizing writes in general so that if a given storage cell is updated 5 times, only the last one will be written back?

2025-03-24 12:28 UTC, Scooletz commented on src/Nethermind/Nethermind.State/PersistentStorageProvider.cs
> +        if (_toUpdateRoots.Count < 3)
This magic number is killing me 😢

2025-03-24 12:28 UTC, Scooletz commented on src/Nethermind/Nethermind.State/PersistentStorageProvider.cs
> +                GetOrCreateStorage(address, out _);
Why is it needed to create one? Comment please or fix.

2025-03-24 12:28 UTC, Scooletz commented on src/Nethermind/Nethermind.State/PersistentStorageProvider.cs
> +                    ref var change = ref dict.GetValueRefOrNullRef(key);
Why iterate over keys only then to lookup the value `change`?

2025-03-24 12:28 UTC, Scooletz commented on src/Nethermind/Nethermind.State/PersistentStorageProvider.cs
> +                ref var dict = ref CollectionsMarshal.GetValueRefOrNullRef(state.changes, kvp.Key);
This chunk is a direct copy of the single threaded. Could we extract a method maybe?

2025-03-24 12:28 UTC, Scooletz commented on src/Nethermind/Nethermind.State/StateProvider.cs
> +            foreach (var key in _blockChanges.Keys)
Similar as above, why loop over to then get the value manually? I don't believe it's cheaper, the lookup hashes the key while the iterator over kvp just scans, right?

2025-03-24 12:28 UTC, Scooletz commented on src/Nethermind/Nethermind.State/StateProvider.cs
> +            if (writes > 0)
A repeated chunk. I'd extract `ReportWrites(writes, skipped)`

2025-03-24 12:28 UTC, Scooletz commented on src/Nethermind/Nethermind.State/IWorldState.cs
> +    void Commit(IReleaseSpec releaseSpec, IWorldStateTracer? tracer, bool isGenesis = false, bool commitRoots = true);
I think this is not the first change in the `IWorldState.Commit`. Should we consider flags maybe for the options, or do you think that `bool commitRoots` will stick for a while and are the only toggle that will be passed down?

2025-03-24 12:28 UTC, Scooletz commented on src/Nethermind/Nethermind.Consensus/Processing/BlockProcessor.cs
> +        _stateProvider.Commit(spec, commitRoots: true);
Am I getting it right that after these, right now, when we access the root hash will be wrong until the final `commitRoots: true` is called, right? I don't see it as a problem in any execution path, but maybe it is?

2025-03-24 12:43 UTC, benaadams commented on src/Nethermind/Nethermind.Db/Metrics.cs
> +[assembly: InternalsVisibleTo("Nethermind.TxPool")]
Mostly is trying to shut them down from being sent to grafana

2025-03-24 12:46 UTC, benaadams commented on src/Nethermind/Nethermind.Consensus/Processing/BlockProcessor.cs
> +        _stateProvider.Commit(spec, commitRoots: true);
Will be currently anyway unless pre-Eip658; doesn't change behaviour in this PR either; if Eip658 not enabled then it will commit the roots at end of tx

2025-03-24 12:48 UTC, benaadams commented
> Isn't it amortizing writes in general so that if a given storage cell is updated 5 times, only the last one will be written back?

This is sorta the case already at the tx level; the change here is moving that to the block level

2025-03-24 12:50 UTC, benaadams commented
> Isn't it amortizing writes in general so that if a given storage cell is updated 5 times, only the last one will be written back?

This is sorta the case already at the tx level; the change here is moving that to the block level.

Also fits with delayed root calculation if that becomes a thing (gathering all the root calculations to the end)

2025-03-24 12:51 UTC, benaadams commented on src/Nethermind/Nethermind.State/PersistentStorageProvider.cs
> +        if (_toUpdateRoots.Count < 3)
< 3 == ❤️ 

Has to be written out in full 😉

2025-03-24 12:56 UTC, benaadams commented
> Looks a bit risky to be honest

Ignore the first commit; which is a bit noisy and refactoring confusing parameter names, dead methods etc

The look at the following two in isolation and isn't that big a change

2025-03-24 14:55 UTC, asdacap commented
![Screenshot_2025-03-24_22-53-12](https://github.com/user-attachments/assets/f24420e5-59bd-4909-9aa1-28c64316ea31)

10% improvement on average mgas/sec. But tend to hangs randomly causing random drop in block/sec. Any idea why?

2025-03-24 15:29 UTC, asdacap commented
![Screenshot_2025-03-24_23-28-50](https://github.com/user-attachments/assets/c48d93ac-4db3-45ea-a28d-cee0fb9aa154)

Dip correlate with lock contention metric.

2025-03-24 15:32 UTC, asdacap commented
![Screenshot_2025-03-24_23-31-44](https://github.com/user-attachments/assets/b1a325bc-e477-4e1e-9eed-ef30647723ce)

In general it spawn much mork thread pool work item.

2025-03-24 15:52 UTC, benaadams commented
> In general it spawn much mork thread pool work item.

Latest change better?

2025-03-24 15:53 UTC, benaadams commented on src/Nethermind/Nethermind.State/StateProvider.cs
> +            if (writes > 0)
Done

2025-03-24 15:53 UTC, benaadams commented on src/Nethermind/Nethermind.State/StateProvider.cs
> +            foreach (var key in _blockChanges.Keys)
Changed

2025-03-24 15:53 UTC, benaadams commented on src/Nethermind/Nethermind.State/PersistentStorageProvider.cs
> +                ref var dict = ref CollectionsMarshal.GetValueRefOrNullRef(state.changes, kvp.Key);
Changed

2025-03-24 15:53 UTC, benaadams commented on src/Nethermind/Nethermind.State/PersistentStorageProvider.cs
> +                    ref var change = ref dict.GetValueRefOrNullRef(key);
Chaned

2025-03-24 15:54 UTC, benaadams commented on src/Nethermind/Nethermind.State/PersistentStorageProvider.cs
> +                GetOrCreateStorage(address, out _);
It can't create them on demand in the parallel loop as the storage dictionary is not concurrent

2025-03-24 15:57 UTC, benaadams commented on src/Nethermind/Nethermind.State/PersistentStorageProvider.cs
> +                GetOrCreateStorage(address, out _);
Added comment

2025-03-24 16:26 UTC, benaadams commented on src/Nethermind/Nethermind.Core/Account.cs
> +        public override int GetHashCode() => throw new NotImplementedException();
Added

2025-03-24 20:51 UTC, benaadams commented
> Seems to work, but lose about 50mgas/sec in the process.

🥲

So keep the parallel, but maybe limit to the min(physical, 16) rather than logical 🤔

2025-03-24 21:15 UTC, benaadams commented on src/Nethermind/Nethermind.Db/Metrics.cs
> +[assembly: InternalsVisibleTo("Nethermind.TxPool")]
Ones in the other projects are mostly incrementing cache hit metrics for a metric that has corresponding Db metric

2025-03-24 23:01 UTC, benaadams commented on src/Nethermind/Nethermind.Trie/Pruning/TinyTreePath.cs
> +    public override int GetHashCode() => (int)BitOperations.Crc32C((uint)_data, ((ulong)_data & 0xffff_ffff_0000_0000) | ~(uint)_data);
Reduced the contention in a couple ways, though this one is of probably most interesting to @asdacap

2025-03-25 12:19 UTC, Scooletz approved these changes
Minor comments, one magic number to clarify if possible.

2025-03-25 12:19 UTC, Scooletz commented on src/Nethermind/Nethermind.State.Test/StorageProviderTests.cs
> +        storageProvider.Commit(Frontier.Instance);
The difference is in the order. CommitTree applies to the tree, so if you commit first, you push the changes in the tree to db and later apply it. Usually it's the other way around.

2025-03-25 12:19 UTC, Scooletz commented on src/Nethermind/Nethermind.State/PersistentStorageProvider.cs
>                  exists = true;
Why then return `exists` in any case? I do understand that in `CollectionsMarshal` it's needed to create the default but here, we always set everything and exists is `true`. I'd remove it even though it won't be aligned with the `CollectionsMarshal`

2025-03-25 12:19 UTC, Scooletz commented on src/Nethermind/Nethermind.State/StateProvider.cs
> +                    change.Before = change.After;
So this is the mutability.

2025-03-25 12:19 UTC, Scooletz commented on src/Nethermind/Nethermind.Trie/TrieNode.Decoder.cs
> +        private const int StackallocByteThreshold = 384;
This magic number requires a comment.

2025-03-25 19:36 UTC, benaadams commented on src/Nethermind/Nethermind.State.Test/StorageProviderTests.cs
> +        storageProvider.Commit(Frontier.Instance);
🤔 Commit doesn't apply to db; moves the "checkpoint" so how far a restore can go, then CommitTree applies to db

2025-03-25 19:37 UTC, benaadams commented on src/Nethermind/Nethermind.State/IWorldState.cs
> +    void Commit(IReleaseSpec releaseSpec, IWorldStateTracer? tracer, bool isGenesis = false, bool commitRoots = true);
Hopefully last change 😉

Mostly just renamed param, as also now effects stateroot

2025-03-25 19:42 UTC, benaadams commented on src/Nethermind/Nethermind.State/PersistentStorageProvider.cs
>                  exists = true;
Only adds on `_missingAreDefault` which is after selfdestruct or creation of a new storage trie at vanilla address (that we know is empty)

2025-03-25 19:49 UTC, merged