Move EnsureCanonical off main loop tx processing
NethermindEth/nethermind pull request #7471
Opened 2024-09-21 13:23 UTC by benaadams

Fixes Closes Resolves #

_Please choose one of the keywords above to refer to the issue this PR solves followed by the issue number (e.g. Fixes #000). If no issue number, remove the line. Also, remove everything marked optional that is not applicable. Remove this note after reading._

## Changes

- _List the changes_

## Types of changes

#### What types of changes does your code introduce?

- [ ] Bugfix (a non-breaking change that fixes an issue)
- [ ] New feature (a non-breaking change that adds functionality)
- [ ] Breaking change (a change that causes existing functionality not to work as expected)
- [ ] Optimization
- [ ] Refactoring
- [ ] Documentation update
- [ ] Build-related changes
- [ ] Other: _Description_

## Testing

#### Requires testing

- [ ] Yes
- [ ] No

#### If yes, did you write tests?

- [ ] Yes
- [ ] No

#### Notes on testing

_Optional. Remove if not applicable._

## Documentation

#### Requires documentation update

- [ ] Yes
- [ ] No

_If yes, link the PR to the docs update or the issue with the details labeled `docs`. Remove if not applicable._

#### Requires explanation in Release Notes

- [ ] Yes
- [ ] No

_If yes, fill in the details here. Remove if not applicable._

## Remarks

_Optional. Remove if not applicable._

2024-09-21 17:59 UTC, LukaszRozmej requested changes
This is very much by design. If we move this to background thread we allow a situation where Head is already changed, but receipts cannot be found for given transactions through RPC. Data inconsistency for the user.

This is generally not acceptable in normal processing. Although we could design a separate batch mode for archive sync where this happens.

2024-09-22 15:57 UTC, smartprogrammer93 requested changes
Yeah, maybe only on Archive or we can also do it under a certain flag in the configs. this way if someone wants the absolute speed, they can ignore receipts being consistent with head

2024-10-02 18:01 UTC, benaadams commented
> Yeah, maybe only on Archive or we can also do it under a certain flag in the configs. this way if someone wants the absolute speed, they can ignore receipts being consistent with head

Or add a cache for recent receipts?

2024-10-03 04:43 UTC, benaadams commented
> This is generally not acceptable in normal processing. Although we could design a separate batch mode for archive sync where this happens.

Added change work?

2024-10-03 07:17 UTC, LukaszRozmej commented
> > This is generally not acceptable in normal processing. Although we could design a separate batch mode for archive sync where this happens.
> 
> Added change work?

Not really, so one could subscribe to newhead subscription or just pull from standard rpc and then not find the receipts. Would be bad.

We need to delay the tree head to be completely safe.

2026-07-09 08:16 UTC, benaadams commented
Superceded by https://github.com/NethermindEth/nethermind/pull/12349

2026-07-09 08:16 UTC, closed without merging