7591 abi encoding optimization
NethermindEth/nethermind pull request #7617
Opened 2024-10-16 15:17 UTC by ssonthal

Fixes Closes Resolves #7591 

_Please choose one of the keywords above to refer to the issue this PR solves followed by the issue number (e.g. Fixes #000). If no issue number, remove the line. Also, remove everything marked optional that is not applicable. Remove this note after reading._

## Changes

- _List the changes_

## Types of changes

#### What types of changes does your code introduce?

- [ ] Bugfix (a non-breaking change that fixes an issue)
- [ ] New feature (a non-breaking change that adds functionality)
- [ ] Breaking change (a change that causes existing functionality not to work as expected)
- [x] Optimization
- [ ] Refactoring
- [ ] Documentation update
- [ ] Build-related changes
- [ ] Other: _Description_

## Testing

#### Requires testing

- [] Yes
- [x] No

#### If yes, did you write tests?

- [ ] Yes
- [x] No

## Documentation

#### Requires documentation update

- [ ] Yes
- [x] No

_If yes, link the PR to the docs update or the issue with the details labeled `docs`. Remove if not applicable._

#### Requires explanation in Release Notes

- [ ] Yes
- [x] No

2024-10-16 15:31 UTC, ssonthal commented on src/bench_precompiles
Please ignore this file. Will undo these changes once I have some confirmations from your end.

2024-10-21 03:43 UTC, ssonthal commented
Hey @LukaszRozmej , awaiting your feedback on this.

2024-10-21 10:39 UTC, LukaszRozmej requested changes
hard  to say without example usages, the one for address doesn't do much

2024-10-21 10:39 UTC, LukaszRozmej commented on src/Nethermind/Nethermind.Abi/AbiAddress.cs
> +                            return nettyAbiStream.AsSpan().ToArray();
you allocate both list and array, not achieving goal of removing allocations

2024-10-22 03:54 UTC, ssonthal commented
I understand. Let me go over this again and get back.

2024-11-14 17:20 UTC, ssonthal commented
Closing this PR. Starting the work again on a new PR.

2024-11-14 17:20 UTC, closed without merging