Build more profitable blocks
NethermindEth/nethermind pull request #7640
Opened 2024-10-21 16:01 UTC by benaadams

## Changes

- _List the changes_

## Types of changes

#### What types of changes does your code introduce?

- [ ] Bugfix (a non-breaking change that fixes an issue)
- [ ] New feature (a non-breaking change that adds functionality)
- [ ] Breaking change (a change that causes existing functionality not to work as expected)
- [ ] Optimization
- [ ] Refactoring
- [ ] Documentation update
- [ ] Build-related changes
- [ ] Other: _Description_

## Testing

#### Requires testing

- [ ] Yes
- [ ] No

#### If yes, did you write tests?

- [ ] Yes
- [ ] No

#### Notes on testing

_Optional. Remove if not applicable._

## Documentation

#### Requires documentation update

- [ ] Yes
- [ ] No

_If yes, link the PR to the docs update or the issue with the details labeled `docs`. Remove if not applicable._

#### Requires explanation in Release Notes

- [ ] Yes
- [ ] No

_If yes, fill in the details here. Remove if not applicable._

## Remarks

_Optional. Remove if not applicable._

2024-10-25 10:08 UTC, LukaszRozmej requested changes
Extreamly complicated, potentially suboptimal, might have some unforseen issues. Not sure if works at all with parallel block building.

2024-10-25 10:08 UTC, LukaszRozmej commented on src/Nethermind/Nethermind.Consensus/Producers/TxPoolTxSource.cs
> +        }
Really dislike the solution:
1. Sort things multiple times
2. Allocating memory while previous solution was lazy.
3. Prioritizing GasPrice sorting over Nonce sorting first.

`GetOrderedTransactions` where close to optimal, lazy and more readable solution and I would prefer to keep it.

2024-10-25 12:29 UTC, benaadams commented on src/Nethermind/Nethermind.Consensus/Processing/BlockProcessor.BlockProductionTransactionPicker.cs
> -
Isn't gas used is limit; so this test excludes txs that could fit but have a higher limit than they use

2024-10-25 12:31 UTC, benaadams commented on src/Nethermind/Nethermind.Merge.Plugin/BlockProduction/BlockImprovementContext.cs
> +        ImprovementTask = Task.Run(() => blockProducer
It currently delays FCU by about 10ms

2024-10-28 09:18 UTC, marcindsobczak commented
We have a `gasBottleneck`, which is 0 for non-ready txs and positive for ready ones. When you want to build an optimal block, you can just sort txs by gas bottleneck (it is actually default sorting) and just pick one by one up to the block gas limit (but only positive values)

2024-10-28 09:22 UTC, marcindsobczak commented
From PR description:
`Sort mempool tx by priority fee of first transaction by sender; maintain nonce order for a sender's txs and priority fee otherwise (e.g. nonce 2 with priority fee 100 doesn't go ahead of nonce 1 with priority fee 50)`
It is already managed by gas bottleneck, you can just reuse it.
To be clear - if sender has tx with nonce N and price 10 gwei and tx with nonce N+1 and price 100 gwei, gas bottleneck of both is equal 10 gwei and both will be included before e.g. tx from other sender, with nonce first to be executed, but with price 5 gwei

2024-11-01 12:04 UTC, marcindsobczak commented
> > From PR description: `Sort mempool tx by priority fee of first transaction by sender; maintain nonce order for a sender's txs and priority fee otherwise (e.g. nonce 2 with priority fee 100 doesn't go ahead of nonce 1 with priority fee 50)` It is already managed by gas bottleneck, you can just reuse it. To be clear - if sender has tx with nonce N and price 10 gwei and tx with nonce N+1 and price 100 gwei, gas bottleneck of both is equal 10 gwei and both will be included before e.g. tx from other sender, with nonce first to be executed, but with price 5 gwei
> 
> I think this won't build optimal blocks, so for example it is better to include transactions with priority fee 10 and next 100, than the one from other sender with fee 20, but that 2nd one will win on gasBottleneck

Right, as long as all of them are able to pay for base fee. In this example - tx with fee 10 must be able to pay base fee by itself to make it possible to process tx with fee 100

2025-03-14 10:10 UTC, benaadams commented
Superceaded by https://github.com/NethermindEth/nethermind/pull/8365

2025-03-14 10:10 UTC, closed without merging