Cache message to Debug logs
NethermindEth/nethermind pull request #7677
Opened 2024-10-29 10:26 UTC by benaadams

## Changes

- Move cache messages to Debug rather than Warm

## Types of changes

#### What types of changes does your code introduce?

- [x] Bugfix (a non-breaking change that fixes an issue)

## Testing

#### Requires testing

- [x] No

2024-10-29 10:44 UTC, LukaszRozmej requested changes
Identify and potentially fix the root cause

2024-10-30 13:18 UTC, LukaszRozmej approved these changes

2024-10-30 13:19 UTC, LukaszRozmej commented on src/Nethermind/Nethermind.Consensus/Processing/BlockProcessor.cs
> +                        if (_logger.IsDebug) _logger.Debug($"Low txs, caches {result} are not empty. Clearing them.");
keep it as Warn though?

2024-10-30 13:19 UTC, LukaszRozmej requested changes
keep as warnings for now?

2024-10-30 17:03 UTC, benaadams commented on src/Nethermind/Nethermind.Consensus/Processing/BlockCachePreWarmer.cs
> +                if (_logger.IsDebug) _logger.Debug($"Caches {result} are not empty. Clearing them.");
```suggestion
                if (_logger.IsDebug) _logger.Warn($"Caches {result} are not empty. Clearing them.");
```

2024-10-30 17:03 UTC, benaadams commented on src/Nethermind/Nethermind.Consensus/Processing/BlockProcessor.cs
> +                        if (_logger.IsDebug) _logger.Debug($"Low txs, caches {result} are not empty. Clearing them.");
```suggestion
                        if (_logger.IsDebug) _logger.Warn($"Low txs, caches {result} are not empty. Clearing them.");
```

2024-10-30 17:03 UTC, benaadams commented on src/Nethermind/Nethermind.Consensus/Processing/BlockProcessor.cs
> +                        if (_logger.IsDebug) _logger.Debug($"Low txs, caches {result} are not empty. Clearing them.");
Changed to warn

2024-10-31 17:48 UTC, LukaszRozmej reviewed
But you left `IsDebug`?

2024-11-23 01:42 UTC, benaadams commented
> But you left `IsDebug`?

Changed back to Warn

2024-11-24 17:00 UTC, merged