Add client id to `admin_peers` RPC API
NethermindEth/nethermind pull request #7706
Opened 2024-11-04 06:42 UTC by anhnhgutech

Add client id to `admin_peers` RPC API 

Related https://github.com/NethermindEth/nethermind/issues/7536

## Changes

- Add id to `admin_peers` RPC API 
- Update `clientId` -> `name`

## Types of changes

#### What types of changes does your code introduce?

- [x] Bugfix (a non-breaking change that fixes an issue)
- [x] New feature (a non-breaking change that adds functionality)
- [ ] Breaking change (a change that causes existing functionality not to work as expected)
- [ ] Optimization
- [ ] Refactoring
- [ ] Documentation update
- [ ] Build-related changes
- [ ] Other: _Description_

## Testing

#### Requires testing

- [x] Yes
- [ ] No

#### If yes, did you write tests?

- [ ] Yes
- [x] No

#### Screenshots
<img width="1258" alt="Screenshot 2024-11-04 at 13 42 38" src="https://github.com/user-attachments/assets/501fd963-24a4-4449-a680-1c15441f208a">

2024-11-04 09:34 UTC, LukaszRozmej approved these changes

2024-11-04 09:34 UTC, LukaszRozmej commented on src/Nethermind/Nethermind.JsonRpc/Modules/Admin/PeerInfo.cs
> +            return (publicKeyBytes is null ? Keccak.Zero : Keccak.Compute(publicKeyBytes)).ToString(false);
We can avoid allocation with:

```suggestion
            return (publicKeyBytes is null ? Keccak.Zero.ValueHash256 : ValueKeccak.Compute(publicKeyBytes)).ToString(false);
```

2024-11-04 09:36 UTC, LukaszRozmej commented
> Regarding updating the clientId parameter to name, I believe that refers to the client name. However, I've only updated it in the admin_peers RPC API, keeping clientId unchanged in other functions.

Where else should we check?

2024-11-04 09:42 UTC, anhnhgutech commented
> > Regarding updating the clientId parameter to name, I believe that refers to the client name. However, I've only updated it in the admin_peers RPC API, keeping clientId unchanged in other functions.
> 
> Where else should we check?

You use `ClientId` in many places, but I think it is currently like a client name, right? 
In this PR, I only updated the API; if you want, I can create another PR to change all var name `ClientId` to `ClientName`
Ex: 
https://github.com/NethermindEth/nethermind/blob/1318d5287af60a09de744f72bc45248feb438b2a/src/Nethermind/Nethermind.Network/P2P/Messages/HelloMessage.cs#L15

2024-11-04 09:55 UTC, LukaszRozmej commented
> > > Regarding updating the clientId parameter to name, I believe that refers to the client name. However, I've only updated it in the admin_peers RPC API, keeping clientId unchanged in other functions.
> > 
> > 
> > Where else should we check?
> 
> You use `ClientId` in many places, but I think it is currently like a client name, right? In this PR, I only updated the API; if you want, I can create another PR to change all var name `ClientId` to `ClientName` Ex:
> 
> https://github.com/NethermindEth/nethermind/blob/1318d5287af60a09de744f72bc45248feb438b2a/src/Nethermind/Nethermind.Network/P2P/Messages/HelloMessage.cs#L15

Nah lets leave P2P messages out of this, it is a different context.

2024-11-04 10:07 UTC, anhnhgutech commented on src/Nethermind/Nethermind.JsonRpc/Modules/Admin/PeerInfo.cs
> +            Id = CalculateClientId(peer.Node.Id);
I see, let me check again.

2024-11-04 15:52 UTC, anhnhgutech commented on src/Nethermind/Nethermind.JsonRpc/Modules/Admin/PeerInfo.cs
> +            Id = CalculateClientId(peer.Node.Id);
I see that IdHash is calculated by `PrefixedBytes`, this isn’t the clientId.
```
IdHash = Keccak.Compute(PublicKey.PrefixedBytes);
```
I think we should use new `CalculateClientId` function, right?

2024-11-04 16:45 UTC, LukaszRozmej commented on src/Nethermind/Nethermind.JsonRpc/Modules/Admin/PeerInfo.cs
> +            Id = CalculateClientId(peer.Node.Id);
Yeah `IdHash` should be fine

2024-11-04 16:47 UTC, LukaszRozmej requested changes
Change to `IdHash`

2024-11-05 00:32 UTC, anhnhgutech commented
> Change to `IdHash`
@LukaszRozmej 
I mean, the `IdHash` doesn't seem to be the same as `ClientId`, they are different.
By the way, as you can see, in `admin_nodeInfo`, the Nethermind team calculates `ClientId` the same way as in my PR

https://github.com/NethermindEth/nethermind/blob/458266e4769609bf4e6826bf6df89495f32f752f/src/Nethermind/Nethermind.JsonRpc/Modules/Admin/AdminRpcModule.cs#L49-L61

2024-11-05 08:32 UTC, LukaszRozmej commented
Closing in favor of https://github.com/NethermindEth/nethermind/pull/7717

2024-11-05 08:32 UTC, closed without merging