7746 inital changes for confirmation
NethermindEth/nethermind pull request #7758
Opened 2024-11-14 09:08 UTC by ssonthal

Fixes Closes Resolves #

_Please choose one of the keywords above to refer to the issue this PR solves followed by the issue number (e.g. Fixes #000). If no issue number, remove the line. Also, remove everything marked optional that is not applicable. Remove this note after reading._

## Changes

- _List the changes_

## Types of changes

#### What types of changes does your code introduce?

- [x] Bugfix (a non-breaking change that fixes an issue)
- [ ] New feature (a non-breaking change that adds functionality)
- [ ] Breaking change (a change that causes existing functionality not to work as expected)
- [ ] Optimization
- [ ] Refactoring
- [ ] Documentation update
- [ ] Build-related changes
- [ ] Other: _Description_

## Testing

#### Requires testing

- [ ] Yes
- [ ] No

#### If yes, did you write tests?

- [ ] Yes
- [ ] No

#### Notes on testing

_Optional. Remove if not applicable._

## Documentation

#### Requires documentation update

- [ ] Yes
- [ ] No

_If yes, link the PR to the docs update or the issue with the details labeled `docs`. Remove if not applicable._

#### Requires explanation in Release Notes

- [ ] Yes
- [ ] No

_If yes, fill in the details here. Remove if not applicable._

## Remarks

_Optional. Remove if not applicable._

2024-11-16 18:04 UTC, ssonthal commented
Hey @obasekiosa , gentle reminder for your review on this one.

2024-11-18 12:06 UTC, LukaszRozmej commented
I am not sure if we should update one path based on another or handle it deeper when resolving the path. @rubo ?

2024-11-18 12:17 UTC, ssonthal commented
Yes, i will fix the submodule changes.

2024-11-18 13:12 UTC, rubo requested changes

2024-11-18 13:12 UTC, rubo commented on src/Nethermind/Nethermind.Runner/Ethereum/Steps/StartRpc.cs
> +            jsonRpcConfig.JwtSecretFile = String.Concat(keyStoreConfig.KeyStoreDirectory,"/jwt-secret");
This change actually introduces another bug disrespecting the `JsonRpc.JwtSecretFile` setting. I think we should remove the default value of the `IJsonRpcConfig.JwtSecretFile` and check for null. If null, then apply this change.

2024-11-18 13:42 UTC, closed without merging

2024-11-18 13:45 UTC, ssonthal commented
Creating a new PR for the suggested changes as I wasn't able to undo the submodule changes - https://github.com/NethermindEth/nethermind/pull/7765