#7748 first changes
NethermindEth/nethermind pull request #7797
Opened 2024-11-23 15:35 UTC by ssonthal

Fixes Closes Resolves #7748 

_Please choose one of the keywords above to refer to the issue this PR solves followed by the issue number (e.g. Fixes #000). If no issue number, remove the line. Also, remove everything marked optional that is not applicable. Remove this note after reading._

## Changes

- _List the changes_

## Types of changes

#### What types of changes does your code introduce?

- [ ] Bugfix (a non-breaking change that fixes an issue)
- [ ] New feature (a non-breaking change that adds functionality)
- [ ] Breaking change (a change that causes existing functionality not to work as expected)
- [ ] Optimization
- [ ] Refactoring
- [ ] Documentation update
- [ ] Build-related changes
- [ ] Other: _Description_

## Testing

#### Requires testing

- [ ] Yes
- [ ] No

#### If yes, did you write tests?

- [ ] Yes
- [ ] No

#### Notes on testing

_Optional. Remove if not applicable._

## Documentation

#### Requires documentation update

- [ ] Yes
- [ ] No

_If yes, link the PR to the docs update or the issue with the details labeled `docs`. Remove if not applicable._

#### Requires explanation in Release Notes

- [ ] Yes
- [ ] No

_If yes, fill in the details here. Remove if not applicable._

## Remarks

_Optional. Remove if not applicable._

2024-11-25 12:46 UTC, obasekiosa commented
@ssonthal 
logic looks good.

a few things to improve would be:
1) removing the old logs that which additional rpc endpoints were activated(added)
2) making the table cleaner -- spacing, header alingment, and column seperator alignments (+)

(1) is a bit straight forward, find the location of the logic that logs that info within the code and then figure out how much of it to remove. 

to help with (2) -- if you look at the logs after a considerable amount of time syncing you'll notice there's a table that built for showing the sync stats. You can take a look at the code that built that and try adapting it.

2024-11-27 05:42 UTC, ssonthal commented
> @ssonthal logic looks good.
> 
> a few things to improve would be:
> 
> 1. removing the old logs that which additional rpc endpoints were activated(added)
> 2. making the table cleaner -- spacing, header alingment, and column seperator alignments (+)
> 
> (1) is a bit straight forward, find the location of the logic that logs that info within the code and then figure out how much of it to remove.
> 
> to help with (2) -- if you look at the logs after a considerable amount of time syncing you'll notice there's a table that built for showing the sync stats. You can take a look at the code that built that and try adapting it.

Hey, I couldn't find any table you mentioned in point (2).  how long do I need to keep the server running to see the sync stats?

2024-11-27 18:53 UTC, obasekiosa commented
> @obasekiosa Regarding point 1, i can only see these logs related to additionalRpcUrls ->
> 
> ![Screenshot 2024-11-27 at 8 41 28 PM](https://private-user-images.githubusercontent.com/54079322/390465099-df169d4d-3b30-4337-8c1f-cfa0b27d7951.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3MzM3NzAsIm5iZiI6MTczMjczMzQ3MCwicGF0aCI6Ii81NDA3OTMyMi8zOTA0NjUwOTktZGYxNjlkNGQtM2IzMC00MzM3LThjMWYtY2ZhMGIyN2Q3OTUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI3VDE4NTExMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzMDlhMDNiZGY3NmQxNzYxNzU3NjU5ZmI5NzQ2NjFjYTE0Yzk5YzE0YjQ3OGNmMjYzMzUzYjNjYjdmMThjOTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.kLYA8oYw8yHoYCtGj2jDlGM9U8bhP9fPtFYE5PbKtJw)
> 
> They don't seem like a problem because they are logging for some unlikely cases, it seems. What do you think?

oh no not these logs

so on start of the client you'd see a log that tells you all the additional rpc urls that are active.

2024-11-28 09:31 UTC, obasekiosa commented
@ssonthal 

I may be wrong but it seems you might be finding it hard to find those logs.

This an example of something similar to what they look like.

```sh
Nov 21 04:33:12 eth nethermind[515741]: 21 Nov 04:33:12 | ***** JSON RPC report *****
Nov 21 04:33:12 eth nethermind[515741]: -----------------------------------------------------------------------------------------------------------------------------------------------
Nov 21 04:33:12 eth nethermind[515741]: method                                  | successes |   avg (ms) |   max (ms) |    errors |   avg (ms) |   max (ms) | avg size B | total (kB) |
Nov 21 04:33:12 eth nethermind[515741]: -----------------------------------------------------------------------------------------------------------------------------------------------
Nov 21 04:33:12 eth nethermind[515741]: engine_exchangeCapabilities             |         1 |      5.754 |      5.754 |         0 |      0.000 |      0.000 |        414 |       0.40 |
Nov 21 04:33:12 eth nethermind[515741]: engine_forkchoiceUpdatedV3              |        27 |      3.282 |     20.278 |         0 |      0.000 |      0.000 |        197 |       5.19 |
Nov 21 04:33:12 eth nethermind[515741]: engine_getClientVersionV1               |         1 |     16.563 |     16.563 |         0 |      0.000 |      0.000 |        122 |       0.12 |
Nov 21 04:33:12 eth nethermind[515741]: engine_getPayloadBodiesByRangeV1        |        11 |     47.851 |     80.270 |         0 |      0.000 |      0.000 |    6580647 |   70690.54 |
Nov 21 04:33:12 eth nethermind[515741]: engine_newPayloadV3                     |        26 |     73.069 |    248.753 |         0 |      0.000 |      0.000 |        162 |       4.11 |
Nov 21 04:33:12 eth nethermind[515741]: eth_chainId                             |         3 |      1.718 |      4.174 |         0 |      0.000 |      0.000 |         39 |       0.11 |
Nov 21 04:33:12 eth nethermind[515741]: eth_getBlockByNumber                    |       898 |      1.856 |     10.137 |         0 |      0.000 |      0.000 |      15681 |   13751.88 |
Nov 21 04:33:12 eth nethermind[515741]: eth_getLogs                             |         2 |    162.104 |    309.276 |         0 |      0.000 |      0.000 |     422005 |     824.23 |
Nov 21 04:33:12 eth nethermind[515741]: eth_syncing                             |        17 |      1.387 |     20.526 |         0 |      0.000 |      0.000 |         39 |       0.65 |
Nov 21 04:33:12 eth nethermind[515741]: -----------------------------------------------------------------------------------------------------------------------------------------------
Nov 21 04:33:12 eth nethermind[515741]: TOTAL                                   |       986 |      4.621 |    309.276 |         0 |      0.000 |      0.000 |      88564 |   85277.24 |
Nov 21 04:33:12 eth nethermind[515741]: -----------------------------------------------------------------------------------------------------------------------------------------------
Nov 21 04:33:12 eth nethermind[515741]:  
```

2024-11-28 15:06 UTC, ssonthal commented
![Screenshot 2024-11-28 at 8 36 38 PM](https://github.com/user-attachments/assets/d8b34ecb-370e-4f89-8c89-cf2db5da4b7e)

2024-11-28 15:07 UTC, ssonthal commented
hey @obasekiosa , i have removed the '+'s from the edges. and the made the pipe separators red to match the prior implementation.

2024-11-28 15:13 UTC, ssonthal commented
Quesions: 

1. currently the table is getting logged twice. Is that expected? or I should explore that?
2. do you want a headling to the table as well? like the one you shared.

2024-12-02 08:46 UTC, obasekiosa commented
> Questions:
> 
> 1. currently the table is getting logged twice. Is that expected? or I should explore that?
> 2. do you want a heading to the table as well? like the one you shared.

1. normally it shouldn't be logged twice.
so yea explore that

2. Yes a good heading would be nice.

Note: did you see the code that generates the reference table i sent?

2024-12-02 13:00 UTC, ssonthal commented
> > Questions:
> > 
> > 1. currently the table is getting logged twice. Is that expected? or I should explore that?
> > 2. do you want a heading to the table as well? like the one you shared.
> 
> 1. normally it shouldn't be logged twice.
>    so yea explore that
> 2. Yes a good heading would be nice.
> 
> Note: did you see the code that generates the reference table i sent?

Yes, i checked the reference. It's also creating the table manually with same logic. So i thought I can go ahead with mine.

2024-12-05 18:04 UTC, ssonthal commented
Hey @obasekiosa , what do you think?
<img width="849" alt="Screenshot 2024-12-05 at 11 34 31 PM" src="https://github.com/user-attachments/assets/e4899bf0-4721-4040-9e1d-7ed104449d58">

2024-12-12 12:38 UTC, ssonthal commented
Hey @obasekiosa , need your input here.

2024-12-12 12:47 UTC, obasekiosa commented
> > > Questions:
> > > 
> > > 1. currently the table is getting logged twice. Is that expected? or I should explore that?
> > > 2. do you want a heading to the table as well? like the one you shared.
> > 
> > 
> > 
> > 1. normally it shouldn't be logged twice.
> >    so yea explore that
> > 2. Yes a good heading would be nice.
> > 
> > Note: did you see the code that generates the reference table i sent?
> 
> Yes, i checked the reference. It's also creating the table manually with same logic. So i thought I can go ahead with mine.

ahh seems i was mixing it up with the paprika repo. 😅

2024-12-12 12:47 UTC, obasekiosa commented
> Hey @obasekiosa , need your input here.

i'd take a look at it.

2024-12-17 02:44 UTC, ssonthal commented
> > Hey @obasekiosa , need your input here.
> 
> i'd take a look at it.

@obasekiosa  gentle nudge for this thread.

2024-12-17 11:41 UTC, obasekiosa commented on src/Nethermind/Nethermind.JsonRpc/JsonRpcUrlCollection.cs
> +        string redSeparator = "\u001b[31m|\u001b[0m";
make static constant at class level.

2024-12-17 11:46 UTC, obasekiosa approved these changes
outside a few tiny changes looks ok.

2024-12-17 13:44 UTC, obasekiosa commented on src/Nethermind/Nethermind.JsonRpc/JsonRpcUrlCollection.cs
> +        _logger.Info("\u001b[31m*****\u001b[0m Additional RPC URLs \u001b[31m*****\u001b[0m");
change this to rpc urls.

2024-12-17 13:54 UTC, obasekiosa commented on src/Nethermind/Nethermind.JsonRpc/JsonRpcUrlCollection.cs
>          foreach (string additionalRpcUrl in _jsonRpcConfig.AdditionalRpcUrls)
add a first row | default | <protocol list> | <modules list>|.
This contains the enabled modules / protocols for the client it self.
https://docs.nethermind.io/fundamentals/configuration/#jsonrpc-enabledmodules
https://docs.nethermind.io/fundamentals/configuration/#jsonrpc-port
https://docs.nethermind.io/fundamentals/configuration/#jsonrpc-host



the ones below are not necessary but if you could find a way to add these to the table that is clear that would be super nice

https://docs.nethermind.io/fundamentals/configuration/#jsonrpc-engineenabledmodules ( these are the protocols for the engine, similar to protocols for additionalrpc.)
https://docs.nethermind.io/fundamentals/configuration/#jsonrpc-enginehost
https://docs.nethermind.io/fundamentals/configuration/#jsonrpc-engineport

2024-12-17 13:55 UTC, obasekiosa requested changes
Just a few minor updates.

2025-12-29 23:54 UTC, vedantd commented
> Just a few minor updates.

Hey @obasekiosa — I’ve been following this PR and the review comments.
I’m happy to help finish up the remaining items (header rename, empty-table handling, first-row RPC info, etc.) and get this over the line if that’s okay.

Let me know if you’d prefer I push commits to this branch or open a follow-up PR.

2026-07-10 02:06 UTC, stdevMac commented
Closing: the underlying issue #7748 was closed as completed on 2026-04-16, so there is no remaining target for this change. Thanks for the contribution.

2026-07-10 02:06 UTC, closed without merging