Implement admin_addTrustedPeer rpc endpoint
NethermindEth/nethermind pull request #7891
Opened 2024-12-11 08:15 UTC by richardgreg

Fixes #7811

## Changes

1. **Added ITrustedNodesManager Interface:**
Created a new ITrustedNodesManager interface to handle trusted nodes. This interface is similar to IStaticNodesManager but for trusted nodes. It provides methods InitAsync(), AddAsync(), RemoveAsync(), IsTrusted(), and exposes Nodes.

1. **Implemented TrustedNodesManager Class:**
Implemented TrustedNodesManager, which reads/writes a trusted nodes file and manages a list of trusted nodes. It also implements INodeSource (or inherits from ITrustedNodesManager : INodeSource) so it can be used by CompositeNodeSource.

1. **Added IsTrusted Property to Node:**
Modified the Node class used by the networking code to include a public bool IsTrusted { get; set; } property. This allows peers to reflect if they originate from trusted nodes.

1. **Integrated TrustedNodesManager into PeerPool:**
Passed an ITrustedNodesManager instance into the PeerPool constructor and updated the peer creation logic (CreateNew methods) to mark nodes as trusted if they come from the trusted nodes manager.

1. **Updated InitializeNetwork to Include TrustedNodesManager:**
Created and initialized TrustedNodesManager inside InitializeNetwork.cs, added it to CompositeNodeSource so that trusted nodes are considered in the node discovery pipeline, and passed it to PeerPool.

1. **Updated IApiWithNetwork and IInitConfig:**

Extended IApiWithNetwork interface to have a ITrustedNodesManager? TrustedNodesManager { get; set; } property (if needed).
Added a TrustedNodesPath property to IInitConfig and InitConfig to define the file path for trusted nodes.
Modified AdminRpcModule Constructor:
Updated the AdminRpcModule constructor to require an ITrustedNodesManager and implemented the admin_addTrustedPeer method using the trusted nodes manager and peer pool.

1. **Updated Tests:**
Adjusted existing tests to provide an ITrustedNodesManager mock where needed. Added a new test (Test_admin_addTrustedPeer) to ensure admin_addTrustedPeer works correctly.

## Types of changes

#### What types of changes does your code introduce?

- [ ] Bugfix (a non-breaking change that fixes an issue)
- [x] New feature (a non-breaking change that adds functionality)
- [ ] Breaking change (a change that causes existing functionality not to work as expected)
- [ ] Optimization
- [ ] Refactoring
- [ ] Documentation update
- [ ] Build-related changes
- [ ] Other: _Description_

## Testing

#### Requires testing

- [x] Yes
- [ ] No

#### If yes, did you write tests?

- [x] Yes
- [ ] No

## Documentation

#### Requires documentation update

- [ ] Yes
- [x] No

_If yes, link the PR to the docs update or the issue with the details labeled `docs`. Remove if not applicable._

#### Requires explanation in Release Notes

- [ ] Yes
- [ ] No

_If yes, fill in the details here. Remove if not applicable._

## Remarks

_Optional. Remove if not applicable._

2024-12-11 12:34 UTC, LukaszRozmej commented on src/Nethermind/Nethermind.Network/PeerPool.cs
> +
I think this logic should be in `PeerManager` or `NodesLoader` rather than in `PeerPool`?

2024-12-11 12:35 UTC, LukaszRozmej commented on src/Nethermind/Nethermind.Network/PeerPool.cs
> +            }
Can be simplified:
```suggestion
            arg.Node.IsTrusted = _trustedNodesManager.IsTrusted(enodeString);
```

2024-12-11 12:41 UTC, LukaszRozmej commented on src/Nethermind/Nethermind.Network/TrustedNodes/TrustedNodesManager.cs
> +            }
Have you considered reusing `NetworkNode.ParseNodes`? Check `NodesLoader`.

2024-12-11 12:42 UTC, LukaszRozmej commented on src/Nethermind/Nethermind.Network/TrustedNodes/TrustedNodesManager.cs
> +            }
Why do we need a channel?

2024-12-11 12:43 UTC, LukaszRozmej commented on src/Nethermind/Nethermind.Network/iTrustedNodesManager.cs
> +        bool IsTrusted(string enode);
Not sure if we should have the interface based on strings? Maybe we should base it on `PublicKeys` or `Enode`?

2024-12-11 12:44 UTC, LukaszRozmej commented on src/Nethermind/Nethermind.Network/PeerPool.cs
> +
Maybe we can avoid it completely as the nodes from source are already marked as trusted?

2024-12-30 16:05 UTC, LukaszRozmej commented on src/Nethermind/Nethermind.Network/TrustedNodes/TrustedNodesManager.cs
> +            string[] nodes = lines.Distinct().ToArray();
I think this is unnecessary, you could load and create network nodes at the same time without allocating

2024-12-30 16:06 UTC, LukaszRozmej commented on src/Nethermind/Nethermind.Network/TrustedNodes/TrustedNodesManager.cs
> +            }
Channel is needed for thread communication, why do you need separate thread here? (IMO you don't)

2025-01-28 12:54 UTC, LukaszRozmej requested changes
Sorry, missed it, still few things to polish

2025-01-28 12:54 UTC, LukaszRozmej commented on src/Nethermind/Nethermind.Network/ITrustedNodesManager.cs
> +    bool IsTrusted(Enode enode);
Something off with indentation

2025-01-28 12:54 UTC, LukaszRozmej commented on src/Nethermind/Nethermind.Network/TrustedNodes/TrustedNodesManager.cs
> +        }
You convert `Node` `ToString`, to convert it to `Enode`, to pass here, to convert it back `ToString`, to create `NetworkNode`, to get `NodeId`, while you had `node.Id` right there in `PeerPool.CreateNew` to begin with as `PublicKey`.

Maybe just make it `public bool IsTrusted(PublicKey key)` ?

2025-01-28 12:54 UTC, LukaszRozmej commented on src/Nethermind/Nethermind.Network/TrustedNodes/TrustedNodesManager.cs
> +                networkNodes.ToDictionary(n => n.NodeId, n => n));
You don't need `lines` not `networkNodes` as intermediate steps (you also create `_nodes` 2 times, once in constructor).
Just add to `_nodes` collection directly in one pass.

2025-01-28 12:54 UTC, LukaszRozmej commented on src/Nethermind/Nethermind.Network/PeerPool.cs
> +
```suggestion
            Node node = new(arg.Node) { IsTrusted = _trustedNodesManager.IsTrusted(arg.Node.NodeId) };
```

2025-01-28 12:54 UTC, LukaszRozmej commented on src/Nethermind/Nethermind.Network/TrustedNodes/TrustedNodesManager.cs
> +        }
Why this isn't fired on node removal?

2025-01-28 12:54 UTC, LukaszRozmej commented on src/Nethermind/Nethermind.Network/TrustedNodes/TrustedNodesManager.cs
> +                JsonSerializer.Serialize(enodes, new JsonSerializerOptions { WriteIndented = true }));
Better to open file as stream and serialize directly into file

2025-01-28 12:54 UTC, LukaszRozmej commented on src/Nethermind/Nethermind.Network/TrustedNodes/TrustedNodesManager.cs
> +            NetworkNode networkNode = new(enode.ToString());
Add `NetworkNode` constructor that takes `Enode` as class and not string to avoid double-conversion.

2025-01-28 12:54 UTC, LukaszRozmej commented on src/Nethermind/Nethermind.Network/TrustedNodes/TrustedNodesManager.cs
> +        }
Or maybe we should also check other parts of Enode like Host and Port and not only PublicKey?

2025-02-04 08:26 UTC, LukaszRozmej requested changes
Few more details, but really close!

2025-02-04 08:26 UTC, LukaszRozmej commented on src/Nethermind/Nethermind.Config/NetworkNode.cs
> +        public NetworkNode(Enode enode) : this(enode.ToString()){}
This is not what I meant
```suggestion
        public NetworkNode(Enode enode) 
        {
          _enode = enode;
        }
```

also put this next to the other constructor

2025-02-04 08:26 UTC, LukaszRozmej commented on src/Nethermind/Nethermind.JsonRpc/Modules/Admin/AdminRpcModule.cs
> +
```suggestion
        if (_trustedNodesManager.IsTrusted(enodeObj) || await _trustedNodesManager.AddAsync(enodeObj, updateFile: true))
        {
          _peerPool.GetOrAdd(new NetworkNode(enodeObj));
          return ResultWrapper<bool>.Success(true);                        
        }
        else
        {
          return ResultWrapper<bool>.Fail("Failed to add trusted peer.");
        }
    }

```

2025-02-04 08:26 UTC, LukaszRozmej commented on src/Nethermind/Nethermind.Network/PeerPool.cs
> +
You need to expose `Enode` property from `NetworkNode` (only `get`):

```suggestion
            Node node = new(arg.Node) { IsTrusted = _trustedNodesManager.IsTrusted(arg.Node.Enode) };
```

2025-02-04 08:26 UTC, LukaszRozmej commented on src/Nethermind/Nethermind.Network/TrustedNodes/TrustedNodesManager.cs
> +            if (nodes.Any() && _logger.IsDebug)
```suggestion
            if (_logger.IsDebug && nodes.Any())
```

2025-02-04 08:26 UTC, LukaszRozmej commented on src/Nethermind/Nethermind.Network/TrustedNodes/TrustedNodesManager.cs
> +                }
generally we do those `if` for log levels as one-liners, to avoid cluttering code

```suggestion
                if (_logger.IsDebug) _logger.Debug($"Trusted nodes file not found at: {_trustedNodesPath}");
```

2025-02-06 12:26 UTC, LukaszRozmej approved these changes

2025-02-06 12:26 UTC, LukaszRozmej commented on src/Nethermind/Nethermind.Config/NetworkNode.cs
> +        }
Can you put constructor next to the other?

2025-02-06 12:56 UTC, flcl42 commented on src/Nethermind/Nethermind.Network/TrustedNodes/TrustedNodesManager.cs
> +        public async IAsyncEnumerable<Node> DiscoverNodes([EnumeratorCancellation] CancellationToken cancellationToken)
Looks like this method will enumerate nodes on start and will ignore added via RPC until restart. What if we add a channel or so?

2025-02-06 12:57 UTC, flcl42 commented on src/Nethermind/Nethermind.Config/NetworkNode.cs
> +          _enode = enode;
Could you add align it a bit

2025-02-06 13:08 UTC, flcl42 commented on src/Nethermind/Nethermind.Network/TrustedNodes/TrustedNodesManager.cs
> +        public async IAsyncEnumerable<Node> DiscoverNodes([EnumeratorCancellation] CancellationToken cancellationToken)
Oh I see, you tried to use channels. Still seems like adding peers during run is what would be expected from UX perspective. Channel can be created in ctor, it may receive updates in `AddAsync`. Iterate it in `DiscoverNodes`

2025-02-06 13:09 UTC, flcl42 commented
Should we have admin_removeTrustedPeer? Not necessary in this pr.

2025-02-06 13:56 UTC, LukaszRozmej commented on src/Nethermind/Nethermind.Network/TrustedNodes/TrustedNodesManager.cs
> +        public async IAsyncEnumerable<Node> DiscoverNodes([EnumeratorCancellation] CancellationToken cancellationToken)
Hm... so maybe channel made sense here and I misunderstood something.

2025-02-07 07:53 UTC, LukaszRozmej commented on src/Nethermind/Nethermind.Network/TrustedNodes/TrustedNodesManager.cs
> +        private readonly Channel<Node> _nodeChannel = Channel.CreateUnbounded<Node>();
I think we need bounded channel, otherwise potential spam could take down the node? 2^16 limit looks ok to me.

2025-02-07 09:29 UTC, LukaszRozmej approved these changes

2025-02-07 10:35 UTC, LukaszRozmej commented
some tests are failing

2025-02-07 22:30 UTC, flcl42 commented on src/Nethermind/Nethermind.Network/TrustedNodes/TrustedNodesManager.cs
> +            while (await _nodeChannel.Reader.WaitToReadAsync(cancellationToken))
Instead of waiting and doing two `while`s, could you just `_nodeChannel.Reader.ReadAllAsync`

2025-02-12 10:16 UTC, LukaszRozmej commented
> Hi, @LukaszRozmej, could you please give me pointers on tackling the failing tests? 😅

```
  Failed Proof_module_is_registered_if_configured [945 ms]
  Error Message:
   Nethermind.Init.Steps.StepDependencyException : _api.TrustedNodesManager
  Stack Trace:
     at Nethermind.Init.Steps.StepDependencyException.ThrowIfNull(Object argument, String paramName) in /_/src/Nethermind/Nethermind.Init/Steps/StepInitializationException.cs:line 23
   at Nethermind.Init.Steps.RegisterRpcModules.Execute(CancellationToken cancellationToken) in /_/src/Nethermind/Nethermind.Init/Steps/RegisterRpcModules.cs:line 123
   at Nethermind.Runner.Test.Ethereum.Steps.RegisterRpcModulesTests.Proof_module_is_registered_if_configured() in /_/src/Nethermind/Nethermind.Runner.Test/Ethereum/Steps/RegisterRpcModulesTests.cs:line 31
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.GetResult()
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await[TResult](TestExecutionContext context, Func`1 invoke)
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(TestExecutionContext context, Func`1 invoke)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Execution.SimpleWorkItem.<>c__DisplayClass3_0.<PerformWork>b__0()
   at NUnit.Framework.Internal.ContextUtils.<>c__DisplayClass1_0`1.<DoIsolated>b__0(Object _)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at NUnit.Framework.Internal.ContextUtils.DoIsolated(ContextCallback callback, Object state)
   at NUnit.Framework.Internal.ContextUtils.DoIsolated[T](Func`1 func)
   at NUnit.Framework.Internal.Execution.SimpleWorkItem.PerformWork()
```

```
  Failed TestDiscovery [770 ms]
  Error Message:
   Autofac.Core.DependencyResolutionException : An exception was thrown while activating Nethermind.Network.PeerPool.
Data:
  ActivatorChain: Nethermind.Network.PeerPool
  ----> Autofac.Core.DependencyResolutionException : None of the constructors found on type 'Nethermind.Network.PeerPool' can be invoked with the available services and parameters:
Cannot resolve parameter 'Nethermind.Network.ITrustedNodesManager trustedNodesManager' of constructor 'Void .ctor(Nethermind.Network.INodeSource, Nethermind.Stats.INodeStatsManager, Nethermind.Network.INetworkStorage, Nethermind.Network.Config.INetworkConfig, Nethermind.Logging.ILogManager, Nethermind.Network.ITrustedNodesManager)'.

See https://autofac.rtfd.io/help/no-constructors-bindable for more info.
  Stack Trace:
     at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)
   at Autofac.Core.Pipeline.ResolvePipeline.Invoke(ResolveRequestContext context)
   at Autofac.Core.Resolving.Middleware.RegistrationPipelineInvokeMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)
   at Autofac.Core.Resolving.Middleware.SharingMiddleware.<>c__DisplayClass5_0.<Execute>b__0()
   at Autofac.Core.Lifetime.LifetimeScope.CreateSharedInstance(Guid id, Func`1 creator)
   at Autofac.Core.Lifetime.LifetimeScope.CreateSharedInstance(Guid primaryId, Nullable`1 qualifyingId, Func`1 creator)
   at Autofac.Core.Resolving.Middleware.SharingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)
   at Autofac.Core.Resolving.Middleware.CircularDependencyDetectorMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)
   at Autofac.Core.Pipeline.ResolvePipeline.Invoke(ResolveRequestContext context)
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, ResolveRequest& request)
   at Autofac.Core.Resolving.ResolveOperation.ExecuteOperation(ResolveRequest& request)
   at Autofac.Core.Resolving.ResolveOperation.Execute(ResolveRequest& request)
   at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(ResolveRequest& request)
   at Autofac.Core.Lifetime.LifetimeScope.Autofac.IComponentContext.ResolveComponent(ResolveRequest& request)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve(IComponentContext context, Type serviceType, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context)
   at Nethermind.Core.Test.Modules.PseudoNethermindRunner.StartDiscovery(CancellationToken cancellationToken) in /_/src/Nethermind/Nethermind.Core.Test/Modules/PseudoNethermindRunner.cs:line 100
   at Nethermind.Network.Discovery.Test.E2EDiscoveryTests.TestDiscovery() in /_/src/Nethermind/Nethermind.Network.Discovery.Test/E2EDiscoveryTests.cs:line 83
   at Nethermind.Network.Discovery.Test.E2EDiscoveryTests.TestDiscovery() in /_/src/Nethermind/Nethermind.Network.Discovery.Test/E2EDiscoveryTests.cs:line 86
   at Nethermind.Network.Discovery.Test.E2EDiscoveryTests.TestDiscovery() in /_/src/Nethermind/Nethermind.Network.Discovery.Test/E2EDiscoveryTests.cs:line 86
   at Nethermind.Network.Discovery.Test.E2EDiscoveryTests.TestDiscovery() in /_/src/Nethermind/Nethermind.Network.Discovery.Test/E2EDiscoveryTests.cs:line 86
   at Nethermind.Network.Discovery.Test.E2EDiscoveryTests.TestDiscovery() in /_/src/Nethermind/Nethermind.Network.Discovery.Test/E2EDiscoveryTests.cs:line 86
   at Nethermind.Network.Discovery.Test.E2EDiscoveryTests.TestDiscovery() in /_/src/Nethermind/Nethermind.Network.Discovery.Test/E2EDiscoveryTests.cs:line 86
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
   at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await[TResult](TestExecutionContext context, Func`1 invoke)
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(TestExecutionContext context, Func`1 invoke)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Execution.SimpleWorkItem.<>c__DisplayClass3_0.<PerformWork>b__0()
   at NUnit.Framework.Internal.ContextUtils.<>c__DisplayClass1_0`1.<DoIsolated>b__0(Object _)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at NUnit.Framework.Internal.ContextUtils.DoIsolated(ContextCallback callback, Object state)
   at NUnit.Framework.Internal.ContextUtils.DoIsolated[T](Func`1 func)
   at NUnit.Framework.Int [...]

2025-02-12 10:20 UTC, LukaszRozmej commented
Also please update to newest master and resolve conflicts

2025-02-14 09:16 UTC, LukaszRozmej approved these changes

2025-02-14 10:40 UTC, flcl42 approved these changes

2025-02-14 15:18 UTC, merged

2025-02-16 08:35 UTC, LukaszRozmej commented
Caused regression, that was fixed in #8211

2025-10-15 15:11 UTC, rubo commented on src/Nethermind/Nethermind.Network/TrustedNodes/TrustedNodesManager.cs
> +            await foreach (string line in File.ReadLinesAsync(_trustedNodesPath))
Here, it reads the file line by line like a new-line-delimited file, but later it writes a JSON array below in `SaveFileAsync`. How is it supposed to work? It fails to read the data written by its own. Am I missing something?

2025-10-15 15:12 UTC, rubo commented on src/Nethermind/Nethermind.Network/TrustedNodes/TrustedNodesManager.cs
> +                catch (Exception ex) when (ex is ArgumentException or SocketException)
`SocketException` looks irrelevant here