feat(network): implement EIP-7801 Sharded Blocks Subprotocol (etha)
NethermindEth/nethermind pull request #7973
Opened 2024-12-25 23:08 UTC by crStiv

Implements EIP-7801: Sharded Blocks Subprotocol (etha)
Fixes #7944

## Changes

- Added etha protocol implementation (EIP-7801)
- Implemented message handlers for GetShardedBlocks, ShardedBlocks, and NewShardedBlock
- Added RLP serialization for protocol messages
- Added protocol registration in network initialization
- Added comprehensive test coverage

## Types of changes

#### What types of changes does your code introduce?

- [ ] Bugfix
- [x] New feature
- [ ] Breaking change
- [ ] Optimization
- [ ] Refactoring
- [ ] Documentation update
- [ ] Build-related changes
- [ ] Other

## Testing

#### Requires testing

- [x] Yes
- [ ] No

#### If yes, did you write tests?

- [x] Yes
- [ ] No

#### Notes on testing

Added comprehensive test coverage including:
- Unit tests for message handlers
- Unit tests for message serialization
- Integration tests for protocol flow
- Error handling tests

## Documentation

#### Requires documentation update

- [x] Yes
- [ ] No

Documentation needed for the new etha protocol implementation and its usage.

#### Requires explanation in Release Notes

- [x] Yes
- [ ] No

Added support for EIP-7801 Sharded Blocks Subprotocol (etha), enabling efficient sharded block synchronization between nodes.

## Remarks

This implementation follows the specification defined in EIP-7801 and adds a new subprotocol for handling sharded blocks in Ethereum network communication.

2024-12-30 11:20 UTC, LukaszRozmej reviewed
Not sure about ProtocolHandler, but the messages and serializers could be reused from standard `eth` protocol?

2024-12-31 09:19 UTC, marcindsobczak reviewed
First of all, thank you for your contribution! Generally it looks good, but need some nitpicks. I left a few comments

2024-12-31 09:19 UTC, marcindsobczak commented on src/Nethermind/Nethermind.Init/Steps/InitializeNetwork.cs
> +        _protocolsManager.AddProtocol(_ethaProtocolFactory);
No need for it

2024-12-31 09:19 UTC, marcindsobczak commented on src/Nethermind/Nethermind.Init/Steps/InitializeNetwork.cs
> +
It is unconditional, so should be added to default capabilities. So remove from here, add in `ProtocolsManager.DefaultCapabilities`, adjust tests

2024-12-31 09:19 UTC, marcindsobczak commented on src/Nethermind/Nethermind.Network/P2P/Subprotocols/Etha/EthaProtocol.cs
> +        public override int MessageIdSpaceSize => 3; // Number of messages in protocol
I would put it directly to `EthaProtocolHandler` to make it similar to implementations of other protocols. `EthaProtocol` can be removed.

2024-12-31 09:19 UTC, marcindsobczak commented on src/Nethermind/Nethermind.Network/P2P/Subprotocols/Etha/EthaProtocolFactory.cs
> +        public EthaProtocolFactory(
It's not needed, we can initialize `EthaProtocolHandler` directly where needed. This class can be removed

2024-12-31 09:19 UTC, marcindsobczak commented on src/Nethermind/Nethermind.Network/P2P/Subprotocols/Etha/EthaProtocolHandler.cs
> +
Here we can add data which is currently in `EthaProtocol`

2024-12-31 09:19 UTC, marcindsobczak commented on src/Nethermind/Nethermind.Network/Protocol.cs
> +{
Remove it please and only update `Nethermind.Network.Contract/P2P/Protocol`

2024-12-31 09:19 UTC, marcindsobczak commented on src/Nethermind/Nethermind.Init/Steps/InitializeNetwork.cs
> +        EthaProtocolFactory ethaProtocolFactory)
We don't need it, this class shouldn't be changed at all

2024-12-31 09:19 UTC, marcindsobczak commented on src/Nethermind/Nethermind.Init/Steps/InitializeNetwork.cs
> +        EthaProtocolFactory ethaProtocolFactory)
You can simply undo all changes in this class. What to do instead is described in other comments :)

2024-12-31 09:19 UTC, marcindsobczak commented on src/Nethermind/Nethermind.Network/P2P/Subprotocols/Etha/EthaProtocolHandler.cs
> +                    break;
Would be good to add metrics to all messages. Compare please with implementations of other protocols. But it's just good-to-have, not hard requirement - we can add it later, in another PR

2024-12-31 09:19 UTC, marcindsobczak commented on src/Nethermind/Nethermind.Network/P2P/Subprotocols/Etha/Messages/EthaMessageSerializer.cs
> +    public class GetShardedBlocksMessageSerializer : IMessageSerializer<GetShardedBlocksMessage>
would be good to separate every serializer class to another file

2024-12-31 09:19 UTC, marcindsobczak commented on src/Nethermind/Nethermind.Network/P2P/Subprotocols/Etha/EthaProtocolHandler.cs
> +                    break;
e.g. `GetShardedBlocksReceived` and here `Metrics.GetShardedBlocksReceived++`

2025-01-07 07:53 UTC, marcindsobczak commented
@crStiv you added more metadata and renamed a few things, there is not a single change related to my comments. So previous review is still relevant.

2025-01-07 11:51 UTC, smartprogrammer93 requested changes

2025-01-07 11:51 UTC, smartprogrammer93 commented on src/Nethermind/Nethermind.Network/P2P/Subprotocols/Etha/EthaProtocolHandler.cs
> +                    break;
This handler does not even follow the EIP spec. it is as if this whole implementation was done with an AI generator.
![image](https://github.com/user-attachments/assets/347e6dab-d4c1-4438-bc2a-464d8f687a5c)

2025-01-07 11:54 UTC, smartprogrammer93 commented
Closing as this PR is irrelevant and does not actually address the actual requirement.

2025-01-07 11:54 UTC, closed without merging